### ISSUE TITLE
Disable plex logins

### ISSUE THREAD

**Issue by schambers** [sct/overseerr#1117]
#### Description
Thanks for the beautiful UI and easy setup! Love this project!

There is a way to disable local user login but I'd like to do the same with Plex users. Prior to exposing this publicly, I wouldn't want to allow any plex user to sign into my overseerr instance. This would potentially allow them to browse my library even though they don't have share access on Plex to my libraries.

#### Desired Behavior

Under Plex in settings, have a similar option to "General Settings" where I have an option "Enable Plex User Sign-In", checked by default but if I un-check, plex sign ins are not allowed.

**Comment by sct** [comment]
Only users with access to your plex server can log in with Plex. It's not open to anyone.

**Comment by p5nbTgip0r** [comment]
I think this issue could still be valid. In Ombi there is an option to disable Plex sign-in and I use it because I have managed users under my Plex home. Because they are managed users and don't have actual Plex logins, they have to sign in to Plex through my account. If they decided to sign into Ombi with my Plex details then they would essentially have access to the admin account on Ombi, but being able to disable Plex logins fixes this issue.

Overseerr has the same issue, but (from what I've tried) no solution like Ombi does. Setting a password on the main account in Overseerr doesn't require the second password to complete the sign in, and I can't delete the admin account from a different admin account in order to replace it with a local user.

**Comment by milindpatel63** [comment]
@p5nbTgip0r did you manage to find any solution to this....have the same issue..

**Comment by p5nbTgip0r** [comment]
@milindpatel63 No, unfortunately not. I've just held off on switching the managed users from Ombi to Overseerr. It might be worth opening a new issue since this one doesn't seem to mention managed users, and it doesn't have any activity as of late

**Comment by milindpatel63** [comment]
@p5nbTgip0r 
i forked the current develop branch and modified the login page to remove the plex login button...
i just removed the code in login.tsx file which displayed the plex login button....haven't modified anything else...
https://github.com/milindpatel63/overseerr

don't know much about typescript or javascript, so can't gurantee for sure how much secure the login page is now...
but considering i just remove plex button, so rest functionality should be secure...

you can install mine using
**sudo snap install dianarequest --beta**
i had to change snap package name...
don't know much about docker so can't create a docker image...
