### ISSUE TITLE
Mask sensitive fields in the UI

### ISSUE THREAD

**Issue by samwiseg0** [sct/overseerr#1228]
#### Description

Mask sensitive data such as API keys in the UI. 

#### Desired Behavior

Mask sensitive data such as API keys in the UI. This would help with support as users are sharing screenshots and have to mask this data for help. 

#### Additional Context

N/A

**Comment by TheCatLady** [comment]
How would we handle if a user wants to highlight and copy the text in the API field, though?  (@sct mentioned this when I tried changing the cursor type in a PR.)  I think this is sort of on the user to hide their API key?  And if they don't, they can easily regenerate it?

**Comment by sct** [comment]
> How would we handle if a user wants to highlight and copy the text in the API field, though? (@sct mentioned this when I tried changing the cursor type in a PR.) I think this is sort of on the user to hide their API key? And if they don't, they can easily regenerate it?

We add a button to the side of sensitive inputs the user can click to reveal the text.

**Comment by TheCatLady** [comment]
> We add a button to the side of sensitive inputs the user can click to reveal the text.

Oh hm, that could work.  But this isn't the only sensitive field.  Do we really want to go down this route?  There's lots of items to mask, including URLs, e-mail addresses, etc.  Where do we draw the line?

**Comment by samwiseg0** [comment]
I would say anything that is meant to be secret. Passwords, API keys, tokens, ect. URLs may or may not be sensitive.

**Comment by TheCatLady** [comment]
> I would say anything that is meant to be secret. Passwords, API keys, tokens, ect. URLs may or may not be sensitive.

Oh wait I just realized you might mean the API key input fields for Sonarr/Radarr?  Since those are basically passwords, I wouldn't be opposed to masking those.  But I don't think it'd be good to mask the Overseerr API key or URLs.

**Comment by samwiseg0** [comment]
I vote fo _all_ secrets regardless if they are overseerr ones or not. Then have a standard way to show anything that has been masked like Sct suggested.

**Comment by shark2k** [comment]
> > I would say anything that is meant to be secret. Passwords, API keys, tokens, ect. URLs may or may not be sensitive.
> 
> Oh wait I just realized you might mean the API key input fields for Sonarr/Radarr? Since those are basically passwords, I wouldn't be opposed to masking those (and we can just change the input type to `password` instead of `text`). But I don't think it'd be good to mask the Overseerr API key or URLs.

Curious why you think the API key for Overseerr shouldn't be masked?  I am not a contributor but I use Tautulli and they just pushed a recent update where they masked sensitive information in the settings and they are masking the API that you would use to access Tautulli.  The masked fields all have the eye icon (that is shown as an eye with a slash when the field is masked) that can be toggled on and off to view the masked information.

I agree with @samwiseg0 that masking all secrets is a good idea.
In this day and age, the application should default to masking sensitive information to prevent users from potentially giving that information away accidentally.
While security is everybody's responsibility, if there are things that you guys as the developers can do to help increase that from the outset, that should be what you go for and be a best practice.

(I'm just a jack of all trades, master of none IT person, so that's just my opinion).

-Shark2k

**Comment by sct** [comment]
> I vote fo _all_ secrets regardless if they are overseerr ones or not. Then have a standard way to show anything that has been masked like Sct suggested.

No reason we can't do this. We can make a "sensitive input" component for this.
