### ISSUE TITLE
Personalized Studios and Networks

### ISSUE THREAD

**Issue by costaht** [sct/overseerr#1239]
#### Description

Today the Studio and Networks list is hardcoded, but since other options are accessible through `/discover/movies/studio/126`,  I would like to suggest the addition of a configuration menu to the admin interface where the administrator would be able to enable/disable studio/network as they prefer.

#### Desired Behavior

Create a menu where the administrator can add the Studios ID to be shown respectively or if want to get fancy, a text box where the admin can search for new Studios.

**Comment by TheCatLady** [comment]
This is might be possible for studios, but would require a non-trivial amount of work to implement. We'd have to use TMDb's `/search/company` endpoint (https://developers.themoviedb.org/3/search/search-companies) and create a UI for users to search and add multiple IDs.

I don't think a similar endpoint exists for networks, unfortunately... it's possible that the `/search/company` endpoint returns both networks and studios (this will require some investigation), but if that is the case then it would make it difficult to determine the type of the results that are returned.

**Comment by costaht** [comment]
.

**Comment by costaht** [comment]
Nevermind

**Comment by dalepmay7** [comment]
Late to the party, but I just wanted to add....

The networks and studios that are shown in the discover sliders are defined in:
/src/components/Discover/NetworkSlider/index.tsx
/src/components/Discover/StudioSlider/index.tsx

For one, the image property isn't necessary since the _logo_path_ of the network or studio can be retrieved using only the ID with the tmdb api. Same with the _name_ of the network or studio.

So then, couldn't the docker-compose.yml include a user-specified list of Network and/or Studio IDs that the user wants to add to the sliders on the discover page?
