### ISSUE TITLE
Missing labels in Catalan translate

### ISSUE THREAD

**Issue by dtalens** [sct/overseerr#1349]
#### Description

Tags for movie genres, and series genres are not displayed and "Movie" tag not translate.
![image](https://user-images.githubusercontent.com/6631832/113412714-49200480-93b9-11eb-9ca8-c0a18ecc694e.png)
![image](https://user-images.githubusercontent.com/6631832/113412743-5c32d480-93b9-11eb-9919-1b9b037ae5f0.png)
![image](https://user-images.githubusercontent.com/6631832/113412775-6c4ab400-93b9-11eb-8964-a85b07e9a8b0.png)

#### Version

Overseerr 1.22.0

Please add catalan lenguage in [Overseerr Glossary.](https://hosted.weblate.org/projects/overseerr/glossary/)

**Comment by TheCatLady** [comment]
Hi @dtalens! We actually don't use the Weblate glossary feature, so you only need to worry about translating the items in [Overseerr Frontend](https://hosted.weblate.org/projects/overseerr/overseerr-frontend/).

As for the genre names, those translations come from TMDb.

If you are able, I highly recommend that you join us on [Discord](https://discord.gg/PkCWJSeCk7)! It's a bit easier to communicate there, and you can also chat with other translators and keep up-to-date on development. 😊

Thanks so much for your contributions so far! ❤️

**Comment by TheCatLady** [comment]
@dtalens Ah, thanks for adding those screenshots!

So, unfortunately, as I mentioned previously, we don't translate/localize the genre names ourselves. We simply use the localized names returned by TMDb. In this case, they are returning `null` for all genres for the Catalan locale.  We will likely put in a fix to fall back to the English genre names in cases like this. If you would like to see the genre names translated, you will need to get them translated on TMDb.

As for the "MOVIE" badge, that string isn't being translated because you haven't finished translating all the strings on Weblate. You can review the translations which have been merged by looking in our repository files or reviewing the commit history.

**Comment by dtalens** [comment]
Thanks, there is little translated content in my language on TMDB. In fact, very few movies and TV series have the synopsis translated. It's frustrating!!

**Comment by TheCatLady** [comment]
> Thanks, there is little translated content in my language on TMDB. In fact, very few movies and TV series have the synopsis translated. It's frustrating!!

TMDb content and translations are all provided by the community, so if you see something missing, you should add it! 😉

**Comment by dtalens** [comment]
I made a request to add translations of movie and TV genres. ;)

**Comment by dtalens** [comment]
És possible afegir un idioma principal i afegir un altre idioma secundari a les sol·licituds Overseerr TMDB?. In this way when the content is not in Catalan could see it in Spanish or English.

**Comment by dtalens** [comment]
Is possible add primary language and add other secondary language in Overseerr TMDB requests?. In this way when the content is not in Catalan could see it in Spanish or English.
