### ISSUE TITLE
Request limit not resetting

### ISSUE THREAD

**Issue by cliny** [sct/overseerr#1358]
#### Description

I have request limits set to 3 movies per 1 day. However, I requested 2 movies 2 days ago as one of my users, and the request limit has not reset back to having 3 available.

#### Version

1.22.0

#### Steps to Reproduce
1. set request limit to x movies per 1 day
2. request movie
3. wait at least 1 day (or 2 days in my case)

#### Expected Behavior

 request limit should reset back to X available movies but it doesn't 

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Device:** desktop
- **OS:** arch linux
- **Browser:** firefox

**Additional information**

using global request limit (no override)

**Comment by cliny** [comment]
I'm not sure if this is a bug or if it's on my end. Because after running 'docker rm overseerr', and 'docker-compose up -d', it seems to have reset the limits.

I have requested another movie as a different user again, and I will check in 24 hours if the request limit has reset.

**Comment by cliny** [comment]
I waited 24 hours (actually 25 hours because of daylight savings coming into effect here), and it still hadn't reset the limit.
I restarted the container, still no.
I ran 'docker rm overseerr' and 'docker-compose up -d', still no.

Just wanted to let you know my experience, it may be fixed in the latest develop release?
Is this happening for anyone else? Or is it just on my end

**Comment by cliny** [comment]
Set to 1 day takes 48 hours to reset I think

**Comment by jonocairns** [comment]
@cliny I think the issue here is that the time value is ignored when calculating the quota limit. That means the following scenario can happen. 

- Request limit hit at 3PM.
- Day one of the cooldown period is the next day
- Day two of the cooldown period is the day after that
- Day 3 at 12:01 they are able to request again.

This means that 48 hours + 9 hours (3PM -> 11:59PM on the first day) have passed since requesting = 57 hours.

I added a PR to include the time period but thinking about it a bit more the current implementation seems correct as the wording is around days and not hours. 

If there was a change to be made it'd have also reflect in the UI that it's based on hours rather than days.
