### ISSUE TITLE
Ability to request series per x days under Global Series Request Limit

### ISSUE THREAD

**Issue by XTechLabs** [sct/overseerr#1395]
#### Description

At the moment, We can request x amount of season per x days. Some of my users like to request the entire TV Shows but due to the limit that I have set, they are unable to do so. It would be nice to have more control over what is being requested.

#### Desired Behavior

Having the option to switch between TV show(s), season(s), or episode(s)

#### Additional Context

#342 

![Screenshot_378](https://user-images.githubusercontent.com/8203095/114281655-d76d3980-99fc-11eb-8cb8-16bc530a3a97.png)
^Here is an example

**Comment by samwiseg0** [comment]
Why not just raise the season count to be higher? Per episode requests have already been requested. https://github.com/sct/overseerr/issues/342

If anything is will get changed to per episodes only when the above feature enhancement is implemented. 

I could see where implementing a selector for show, season, or episode could be feasible but not all 3 at the same time as that would be difficult to implement/track.

**Comment by sct** [comment]
I am a little bit confused by this request. You want users to be able to request entire shows but you set a restriction that limits that? Isn't the quota doing its job then? If your limit isn't high enough, raise it? 

I did want to add the option to select what we limit on (series/seasons/episodes) but it's a lower priority for now since seasons should cover most use cases. We decided to start with seasons because it gives a fairly reasonable amount of control over how much content can be requested at once. By just allowing shows, that could easily be thousands of episodes in some cases, and then what purpose does the quota actually serve?

**Comment by XenosTechLabs** [comment]
> I did want to add the option to select what we limit on (series/seasons/episodes) but it's a lower priority for now since seasons should cover most use cases. We decided to start with seasons because it gives a fairly reasonable amount of control over how much content can be requested at once. By just allowing shows, that could easily be thousands of episodes in some cases, and then what purpose does the quota actually serve?

Yes sorry, adding the option to select what we can limit on (series/seasons/episodes).

**Comment by SpartacusIam** [comment]
I'd like to request this issue be re-opened.  The problem with only allowing the quota per season is that you have to put the seasons very high to account for some shows that are 10+ seasons long.  But then that gives users the ability to request 4-5 different series with 1-2 seasons in them.  The ability to allow users to only request X amount of SERIES per X amount of days would be terrific.

**Comment by SpartacusIam** [comment]
I'd still love this feature.

**Comment by XenosTechLabs** [comment]
I would like this to be re-open again

**Comment by XenosTechLabs** [comment]
I would like this to be re-open again

**Comment by SpartacusIam** [comment]
Please keep this open.

**Comment by TechTheKid** [comment]
+1

**Comment by TechTheKid** [comment]
+1
