### ISSUE TITLE
Server Stats/Control Widget

### ISSUE THREAD

**Issue by manor7777** [sct/overseerr#1467]
#### Description

On another request system i know of, it has a feature that will show "Now Playing" for anyone who has an administrator role and has the system connected to plex. It would be great to have a nicely styled widget on the home screen (after you login) that will show now playing (small widget per user, like each recently added), connected IP address, geoip location for that IP, and a terminate stream w/message button

#### Desired Behavior

See above

**Comment by sct** [comment]
This isn't really Overseer's focus though. Maybe it's sorta nice but what does it actually offer you? Tautulli is already much better at doing this.

If someone can give me a really solid use case, as to how having this information in Overseerr is beneficial to them, I might consider it.

**Comment by manor7777** [comment]
I can understand that. Petio (https://petio.tv/) has this and similar functionality - i just thought it would be nice to have

I don't think it's necessary, just thought it would be nice feature - if you added it, would be low priority or someday priority.

**Comment by Dabu-dot** [comment]
To be honest, I don't see any use for this in a request manager.

But if I'm doing devil's job here (also I'm extending it outside of its planned scope), the only use case I would see for server stats to be collected is "post-viewing recommendations".

If the future vision for Overseerr is to achieve modular interface in Discover like hookable custom sliders, studios, genres etc.. I suppose a module for recommandations based on previous medias played per user isn't far enough from the point.

Example: "Because you watched Toy Story recently..." - display Similar Titles slider.

Again, I'm extending it to a part where collecting server stats would make sense in the backend to be re-used later. It would need a significant amount of work and probably be under priority:someday at best. 

It's also far enough from the feature request made here, but that's the only use I could think of for "Server Stats Widget-based".

**Comment by sct** [comment]
> I can understand that. Petio (https://petio.tv/) has this and similar functionality - it is also a request system with radarr/sonarr support - i just thought it would be nice to have

I'm aware Petio has this but we aren't driven by what other request platforms are doing.

> I don't think it's necessary, just thought it would be nice feature - if you added it, would be low priority or someday priority.

I mean, I guess? I don't really have plans to add features that are just "nice" but serve no actual purpose.



> To be honest, I don't see any use for this in a request manager.
> 
> But if I'm doing devil's job here (also I'm extending it outside of its planned scope), the only use case I would see for server stats to be collected is "post-viewing recommendations".
> 
> If the future vision for Overseerr is to achieve modular interface in Discover like hookable custom sliders, studios, genres etc.. I suppose a module for recommandations based on previous medias played per user isn't far enough from the point.
> 
> Example: "Because you watched Toy Story recently..." - display Similar Titles slider.
> 
> Again, I'm extending it to a part where collecting server stats would make sense in the backend to be re-used later. It would need a significant amount of work and probably be under priority:someday at best.
> 
> It's also far enough from the feature request made here, but that's the only use I could think of for "Server Stats Widget-based".

Yeah I mean this is useful information to grab, but it's an entirely separate request. Perhaps recommendations like this are something we can tackle someday in the future. As you said, it's a big undertaking to do (the right way.)

**Comment by manor7777** [comment]
> Yeah I mean this is useful information to grab, but it's an entirely separate request. Perhaps recommendations like this are something we can tackle someday in the future. As you said, it's a big undertaking to do (the right way.)

Ok, that's fair honestly. I'll close this for now unless you want to tag it with a someday priority. Thankyou for the reply
