### ISSUE TITLE
Provide trailer in a fallback language when the original TMDB request doesn't provide one in the chosen localization

### ISSUE THREAD

**Issue by cpt-kuesel** [sct/overseerr#1643]
#### Description

After switching my localization to my mother tongue I noticed that there were movies where trailers where missing, that were there when I used Overseerr in English.
I know that is because the request to TMDb wouldn't return a trailer in the language I've chosen to use Overseerr in.
In my ideal world Overseerr would then provide a trailer in a fallback language to be determined by the admin or even on a per user choice.

#### Desired Behavior

If there is no trailer available in the chosen localization, Overseerr will provide one in a fallback language.

#### Additional Context

My thoughts on this is that this should not be enabled by default because the number of requests to TMDb might/will skyrocket for all those languages Overseerr/TMDb already support. 
Fingers crossed you can find a suitable solution 😄

**Comment by TheCatLady** [comment]
TMDb already has fallback logic built-in (for all requests, not just for trailers).  If there isn't a result for your specific locale, TMDb tries to return something from a similar one.  We shouldn't be re-engineering this IMO.

Also, it's the same experience if you browse the actual TMDb website.  If there is no trailer in your language, the "Play Trailer" option simply does not appear.

Also, the fallback display language for Overseerr is English because it is the language of our source strings; no other language is guaranteed to be completely translated.  Allowing specification of a different fallback language would result in weird UX where there are potentially three different languages shown to the user.

**Comment by cpt-kuesel** [comment]
So TMDb should already have given the english trailer in the example that prompted me to open this issue?

My example was the movie „I am all girls“ where there is no german trailer but an english one at the time of writing.

**Comment by TheCatLady** [comment]
@cpt-kuesel TMDb has logic to fall back to other languages/locales that isn't under our control.  They do fall back to English for some things, but not for trailers.

**Comment by yueyingjuesha** [comment]
I would like to work on this feature since my mother tongue is Mandarin but almost all of the movies and tv shows don't have its trailer, which is quite frustrating, @TheCatLady wondering if you any other thought on the idea of adding fallback language for trailer

**Comment by TheCatLady** [comment]
@yueyingjuesha Please see my comments above. IMO, this is something that should be handled on the TMDb side.

**Comment by StancuFlorin** [comment]
@TheCatLady It looks like TMDb is already doing this. See this movie [1]. I can see the trailer on their website for Romanian language, but sadly I can't see the trailer in Overserr.

Not sure if the TMDb returns the trailer data when the Romanian details are requested.

[1] https://www.themoviedb.org/movie/558449-gladiator-ii?language=ro

**Comment by StancuFlorin** [comment]
Well, I created a PR for this https://github.com/sct/overseerr/pull/4009
