### ISSUE TITLE
Prevent Automatically Approved notifications for those with Manage Requests

### ISSUE THREAD

**Issue by dphildebrandt** [sct/overseerr#1707]
#### Description

I have automatic approval for my users, and I really like the automatic approval notifications so that i can check in on radarr/sonarr occasionally and make sure things are going well. 

But, it's very annoying to receive automatically approved notifications for my own requests. 

#### Desired Behavior

Prevent those with Manage Request permissions from receiving Automatically Approved notifications for their own requests.

**Comment by TheCatLady** [comment]
There are some notification agents that send notifications directly to individual users (e.g., email, web push), and others that send notifications to a channel that isn't necessarily just for one person (e.g., Discord).

In the first case, I agree that we should modify the notification logic so that users do not get notified of their own requests being approved.

**Comment by dphildebrandt** [comment]
Im going to work on this issue this weekend and get a PR out.

**Comment by TheCatLady** [comment]
@dphildebrandt Actually, I already have an open PR for some other changes to the notification agents, and this needs to wait until after that is merged.
