### ISSUE TITLE
Privacy option to disable "Recently Added"

### ISSUE THREAD

**Issue by zwimer** [sct/overseerr#1841]
#### Description

Currently "Recently Added" videos are displayed prominently. This issue is meant to provide a way to disable this for privacy reasons.

#### Desired Behavior

Provide an option in default permissions in settings to hide 'Recently Added'. That is, if this is not a default permission, new users will not get the 'Recently Added' view when they log in.

#### Additional Context

This is not about 'perfect privacy', it is simply about not blatantly advertising what was recently added.

**Comment by sct** [comment]
I don't see what's so private about what was recently added to your Plex? The same information can be found just by browsing Overseerr.

**Comment by zwimer** [comment]
Of course, it isn't about 'perfect privacy' as much as not 'publicly' announcing to each member of your family, of all age groups, what the others recently had added. If they snoop I'm sure they will see it, but if they just use this to request videos then this takes something out of sight / out of mind and places it right in the center where is must be seen.

**Comment by WoisWoi** [comment]
I do not see the benefit from a "privacy" point of view, however, it would be nice to be able to choose where it is displayed or not, since it is currently strongly put forward, it would be nice to have the choice.

**Comment by Epirr** [comment]
It seems to be displaying content from all libraries, rather than just the libraries that the user has permission to view. This can be a problem especially if you have kids and don't want them to see inappropriate content. If library permissions cannot be pulled across (I'm not super technical so I don't know how feasible it would be), would it be possible to just hide the Recently Added section? As they can just use the Recently Added section within Plex itself for their library.

**Comment by Markyb0y** [comment]
I would also like to see this, I use this app as a way for my family to make simple requests, the less clutter on the screen the better as far as they are concerned. Search > Request > Done :)

**Comment by johannvonperfect** [comment]
Just wanted to bump this. I am setting up my Overseerr instance and this issue was one I immediately noted that is kind of a deal-breaking problem in my use case; I also have kids and elderly parents that I don't want seeing various recently added movies and TV shows that they do not have access to on my Plex server.

As @Epirr mentioned above, pulling the permissions from the Plex server would be best but I suspect that is not feasible. Instead, it looks like this issue can be resolved by @TheCatLady's pull request in #2129 which was originally submitted in September 2021. Hopefully it can be implemented soon. Thanks for the hard work.

**Comment by johannvonperfect** [comment]
I wanted to check in again on this feature as another month has passed. The pull request is a net increase of 20 lines of code and has been pending for almost 6 months. Is there anything else that needs to be done to get the ball rolling? Thank you again for your efforts.

**Comment by carterjc** [comment]
Happy to help if possible to get this feature implemented

**Comment by johannvonperfect** [comment]
This issue has been open for a year; the code to resolve the issue in #2129 was initially prepared 9 months ago; and attempts to follow up (mine, anyway) are marked as off-topic or spam. @carterjc and @zwimer have volunteered to help. Is there something else we can do?
