### ISSUE TITLE
Logging options

### ISSUE THREAD

**Issue by th3fallen** [sct/overseerr#1877]
#### Description
It would be amazing if we could configure how verbose the logs are for overseerr, atm it spams the logs an insane amount for every single action

#### Desired Behavior

Add ability to not log info and only log errors/etc

#### Additional Context

Provide any additional information or screenshots that may be relevant or helpful.

**Comment by danshilm** [comment]
The log levels are: `debug`, `info`, `warn`, and `error` in that order, from most verbose to least verbose. You can set that with the `LOG_LEVEL` environment variable.

**Comment by th3fallen** [comment]
perfect! thanks

**Comment by th3fallen** [comment]
So to confirm, if i set it to warn, I'll get warn and above logs correct?

**Comment by danshilm** [comment]
Yes, that's it. 

But keep in mind that this will make debugging things harder since there won't be very useful logs for the time that _something_ went wrong. Plus we have log rotate set up, so even when set on `debug`, it will barely take up any disk space.
In the log viewer, you can also filter with the log level and the behaviour is the same (set the filter to `warn`, you'll only see `warn` level log messages and above).
