### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AyyKamp** [sct/overseerr#1937]
#### Description

Overseerr using 3 to 4 GBs of memory

#### Version

1.25 (also tried newest develop)

#### Screenshots

![image](https://user-images.githubusercontent.com/32194363/127396478-921b748e-8e84-42d7-9826-a33366a92332.png)

![Memory usage of the container over a couple minutes](https://user-images.githubusercontent.com/32194363/127397260-f98b38f1-d774-44f9-98c1-d0d36a6da250.png)

[overseerr-2021-07-28.log](https://github.com/sct/overseerr/files/6896493/overseerr-2021-07-28.log)

#### Device

- **Platform:** vps
- **OS:** Ubuntu 18.04
- **Browser:** n/a

#### Additional Context

Has been happening for a couple days now, no idea why.

**Comment by samwiseg0** [comment]
Are you using the official image? Have you check to make sure you are running the latest docker version? Also can you please enable debug logging and provide updated logs?

I am not seeing this issue nor is anyone else on the dev team? There maybe something different on your system causing this? Since it just started a few days ago and we have not had a new release in weeks. I would suggest you check to see what changed on your system.

**Comment by AyyKamp** [comment]
Updating docker seems to have solved it. I'll update in a couple days if it stayed that way. 

Thanks :)

**Comment by AyyKamp** [comment]
That didnt end up solving it. Deleting the data base and starting new did however.
