### ISSUE TITLE
Add User notes field

### ISSUE THREAD

**Issue by BobOkisama** [sct/overseerr#2009]
#### Description

Feature request to add a notes field in the user accounts.

#### Desired Behavior

When you open a user to edit a separate field should exist to allow me to add notes and aliases.

**Comment by tobyselway** [comment]
Hi, new to this project, but hoping to contribute a bit.

Notes should be straightforward, aliases may have a couple of implications depending on if they're to be used instead of a user's name.

I'll have a look at the code and UI and get back to this issue within the next few days with a screenshot of what I've came up with.

 - TS ☕

**Comment by BobOkisama** [comment]
Aliases should be just as easy, unless you want to fully integrate it throughout the system, which likely would be overkill. Just put it as a separate notes field and just put the visible text descriptor as Aliases. The main want for this is being able to put IRL names to the emails/usernames so when I see user YngThang88 with three logons I can check quickly and go "oh that's my mom, better disown her."

Welcome to the project btw, I am a new user and so far loving it!

**Comment by TheCatLady** [comment]
@BobOkisama Why not just set recognizable display names for your users?

**Comment by BobOkisama** [comment]
Adding a notes field adds nearly an unlimited amount of functionality for the admin. If I want to track requests, preferences, donations, alt emails, phone numbers, really anything that I as the admin might want to collect... that would be added functionality. Maybe I need to track location data or ips for users that shared their account against my wishes or perhaps special sub requirements I need to manually go get.. etc. There is just a metric ton of different things I might need a notes field for.

I will try the Display name/IRL name... I did not think of that and would fit the bill nicely.

**Comment by TheCatLady** [comment]
> Adding a notes field adds nearly an unlimited amount of functionality for the admin. If I want to track requests, preferences, donations, alt emails, phone numbers, really anything that I as the admin might want to collect... that would be added functionality. Maybe I need to track location data or ips for users that shared their account against my wishes or perhaps special sub requirements I need to manually go get.. etc. There is just a metric ton of different things I might need a notes field for.

Tracking location data and IPs is something that Tautulli does already... why would you want to manually input that information?

My view is that most of the data you mentioned is best stored elsewhere, and not in Overseerr.  Shouldn't contact information for your friends/family be stored in your phone or some other address book?  Who is going to open Overseerr, look for the phone number, and then punch it into their phone?

As for subtitles, the issues system (#635) that @sct is building should cover that.

And we are staunchly against Plex resellers, so tracking donations or information on strangers you may share your Plex server with isn't going to be valid justification for an unnecessary feature that has no real functionality.

That said, @sct has the final say on this and he hasn't voiced his opinion yet.

**Comment by BobOkisama** [comment]
I just found the need for a notes field and as a user put that forward. I thought requesting features that currently exist in competing products that I currently use would be useful. If you do not want added user functionality because I can in the end go store it in notepad, that is fine. I can also have users email their requests and add them into radarr/sonarr etc instead of having things in a single location so we do not duplicate functionality. Sorry I submitted the request, please close it.

**Comment by TheCatLady** [comment]
@BobOkisama Feature requests are welcome, but the team does sometimes decide not to implement features.  There has not been a decision made about your request yet.  I'm just voicing my opinion that it wouldn't make sense for us to add this.

When you a submit feature request, you should generally be open to having a discussion about it.  No one asked you to store any information in Notepad.  It simply seems to me like there are better solutions for your use case.  And again, @sct has yet to make a decision on this, so no need to get all huffy.

Also, just because other projects have implemented a feature, doesn't automatically mean that we will be adding it to Overseerr as well.
