### ISSUE TITLE
Allow user to remove value from "Recently Added" pane

### ISSUE THREAD

**Issue by uofirob** [sct/overseerr#2092]
#### Description

Is your feature request related to a problem? Yes #2091 

Sometimes Plex has the correct metadata but it doesn't pull across to Overseerr correctly. I'm frustrated when I'm unable to get it right, so I'd prefer the ability to remove the item from the list for myself or for all users (in this case it was misidentifying a record as anime that had a very suggestive picture, and if I give my wife or friends ability to request, I don't want them to see that.

#### Desired Behavior

On the Recently Added items, add an x to the right on hover that when clicked asks the user if they want to hide the item for themselves or for all users.  set a variable in background that will hide the value from the list.

#### Additional Context

Possibly also add ability to turn off the recently added pane all together.

**Comment by samwiseg0** [comment]
The issue you are experiencing is related to invalid data in Plex. This is not an overserr issue but instead improper or invalid data on Plex. The issue is the inaccurate data in Plex.  I took a look at your metadata and it’s not matched correctly as it’s using local data and not matched to TVDB or TMDB. We can assist you further on discord.

Thanks

**Comment by samwiseg0** [comment]
Also I believe this is a duplicate of https://github.com/sct/overseerr/issues/447. 

If the user is able to find unmatched media or properly match mismatched media then it would resolve this issue.
