### ISSUE TITLE
Request: Ability to show only movies or only tv shows

### ISSUE THREAD

**Issue by coltonshipley** [sct/overseerr#2276]
### Description

I have a use case where I only use automation for movies. I would love if I could configure overseerr to only show movies instead of movies and tv series.

### Desired Behavior

I think if there was a toggle as to what you wanted users to be able to see and/or request. So if I only have movies toggled that is all that will appear thought the entire application.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Beaker66** [comment]
+ 1 for this

**Comment by neruve** [comment]
I would still like to see this implemented.

**Comment by n8detar** [comment]
I also think this would be a good feature, but rather than a single master switch having this option as a permission would work better. On the permissions page under Requests, there could be the option to check a box for TV Shows and one for Movies so unless it is checked the user can't see movies or tv shows or request them. Then under default permissions if you don't want anyone to see movies you don't check that box. This way if you want some users to be able to request only movies and some that can request both movies and tv shows it can be done through permissions.

**Comment by skynet01** [comment]
I agree with n8detar, great idea but it should be per user permission. If you want it global you would just set it as default user permission
