### ISSUE TITLE
Ability to customize an Acceptance/Rejection/Availability Notification?

### ISSUE THREAD

**Issue by winbatch** [sct/overseerr#2295]
### Description

Not for style related stuff on automated notifications, but on an individual basis when manually approving/rejecting, etc it'd be cool to have the option to add some custom text on that particular notification.

### Desired Behavior

Optional checkbox for adding more text, etc.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by samwiseg0** [comment]
duplicate of https://github.com/sct/overseerr/issues/405

**Comment by winbatch** [comment]
I don’t consider it a dupe because I am not asking for templating. I’m just looking at add custom text on *specific* notifications.

**Comment by samwiseg0** [comment]
> I don’t consider it a dupe because I am not asking for templating. I’m just looking at add custom text on _specific_/_one time_ notifications.

That would be covered by this request https://github.com/sct/overseerr/issues/593

I am not sure I see a reason to have additional messaging specific to approvals that would not be covered in modifying a template? 

Available messages are automatically generated so that would fall under the first duplicate issue I linked as the admin is not in control when that happens.
