### ISSUE TITLE
Add Pushover extended options

### ISSUE THREAD

**Issue by bobfatherx** [sct/overseerr#2377]
### Description

Thanks for the Pushover support. It works great, though lacks some customization that is possible using their API. 

### Desired Behavior

Please add the extended API options for Pushover, including the ability to specify the device to push to, priority of the push, and to customize the push sound. Please see the Pushover API site (https://pushover.net/api) for more information.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Priority of push notifications is already set based on the event type.

Specifying device(s) / sounds would be nice, however.

**Comment by TheCatLady** [comment]
Reading over the Pushover documentation, I don't think we should allow specifying of devices due to the inconsistent behavior when a group ID is specified instead of a user ID:
https://pushover.net/api#identifiers
> When sending to delivery groups not belonging to a Pushover for Teams organization, or specifying multiple users in a single request, the `device` parameter will be ignored. Group users will have their specific device honored according to how they are entered in the group.
> 
> When sending to a single Pushover for Teams-owned group, the `device` name _is_ honored, and will restrict sending the message to just the team member devices matching the name in the group. If no devices match, the message will not be broadcast to any users and the API will return a failure status.

And, notifications can be delivered only to specific devices already by creating and using a group ID rather than a user ID.  (When adding users to a group, you can specify devices for that user.)

I'm adding Pushover notification sound options to my to-do list, though.  We will retrieve the list of options via the Pushover API and allow selecting an option from a dropdown.  (Relevant Pushover documentation: https://pushover.net/api#sounds)

**Comment by bobfatherx** [comment]
That is super news. Thank you so much for considering the capability!

**Comment by befantasy** [comment]
The web interface of overseerr is support muti-language. But it seems that the push information doesn't change with the web interface language settings.
