### ISSUE TITLE
Ability to hide "Play on Plex"

### ISSUE THREAD

**Issue by amadotejada** [sct/overseerr#2522]
### Description

I would like to request two things if possible as a feature request 🙏🏽 

1. Ability to hide "Play on Plex" button from content that is already available
1a. Or replace with "Watch Trailer" instead
2. Hide or remove the link on the Plex Icon from the streaming networks

Having this flexibility will give admins the choice to share access to Overseerr with local accounts without confusing the user that they can watch Plex via mobile or exposing the Plex server URL

Thank you!

### Desired Behavior

Have a toggles in settings to enable/disable both buttons

### Additional Context

<img src="https://i.ibb.co/cDQSbGc/Screen-Shot-2022-02-08-at-2-59-17-AM.png" alt="Screen-Shot-2022-02-08-at-2-59-17-AM" border="0">

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
> Having this flexibility will give admins the choice to share access to Overseerr with local accounts without confusing the user that they can watch Plex via mobile or exposing the Plex server URL

Hmmmm. So, there are actually plans to deeplink to the Plex apps on mobile... and the Plex server URL isn't exposed unless you have configured the web app URL in your Overseerr Plex settings.

Do these users not have access to the Plex server at all? 🤔 (Local users were designed for users who don't have their own Plex account, but only profiles on the server owner's account.)

**Comment by amadotejada** [comment]
@TheCatLady Thank you for the reply! These users do not have access to the Plex server with a Plex account.

**Comment by TheCatLady** [comment]
> These users do not have access to the Plex server with a Plex account.

Do they have access to the Plex server at all?  E.g., via a profile on the server owner's account?

If not, how are they accessing the media they request?

**Comment by amadotejada** [comment]
@TheCatLady For these users - I would register their TV devices (firetv,appletv,roku) via the Plex Pin and they won't have their own Plex account. Overseer would then notify them their request is available and go to the TV to watch. This is problaly not a common setup but if this is an optonal toggle it would be awesome.

**Comment by TheCatLady** [comment]
@amadotejada Ah, so they do have Plex server access. Do you have them added as [managed users](https://support.plex.tv/articles/203948776-managed-users/)?  If so, can't you sign them into Plex on other devices (mobile, desktop, etc.) so that they are able to click on the links?

But our recommendation is to [create Plex accounts for your users and add them to your Plex Home](https://support.plex.tv/articles/203815766-what-is-plex-home/), as that gives a better user experience -- your users can then sign into Plex with their own credentials and log in to Overseerr with their Plex account.  (If you use Tautulli, you'll also get Overseerr's upcoming Tautulli integration in the next release, which only works with users with their own Plex accounts.)

**Comment by amadotejada** [comment]
@TheCatLady They are only added to my Plex server as a device, not as a managed users. For example. I would ask my parents to open the Plex app on their AppleTV and click Login. Then they would give me the PIN used in https://www.plex.tv/link/ 

In Overseerr they if they click "Play On Plex" or the Plex icon on the bottom for available content that won't work because they dont have Plex accounts. For this use case Overseerr is used stricly as Local users.
