### ISSUE TITLE
UI reports 1.29.1 is out of date, GH says 1.29.0 is latest

### ISSUE THREAD

**Issue by briancline** [sct/overseerr#2747]
### Description

Today I logged in to Overseerr and noticed the version showing yellow, so of course I click excitedly. On /settings/about, it reports "1.29.1 (Out of Date)". The Out of Date badge takes me to the GitHub releases page, which reports 1.29.0 is the latest version. From there, clicking the Tags button shows that 1.29.1 is the latest version tag.

I've already flushed the GitHub cache from the Jobs & Caches page, but same result.

Did an entry for 1.29.1 get removed from the Releases page or somewhere else?

### Version

1.29.1

### Steps to Reproduce

1. Pull and launch an image for 1.29.1
2. Log into Overseerr
3. Version box is yellow and About page shows Out of Date badge

### Screenshots

![image](https://user-images.githubusercontent.com/32032/167728801-d485c338-708d-4af9-9d92-055b227771c4.png)

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser

Firefox 100.0

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Not sure what happened yesterday with GitHub releases since I'm pretty sure we didn't delete the release or anything like that (the `1.29.1` tag was still there too, just not the release), but it's back to normal now 🤷‍♂️ 
If you don't see the `1.29.1` release as the latest in Overseerr's About page, clear the "GitHub API" cache.
