### ISSUE TITLE
Add movie or TV show as unmonitored

### ISSUE THREAD

**Issue by edgarsuit** [sct/overseerr#2765]
### Description

There are situations where a user may want to add a movie or a TV show to *arr in an unmonitored status. This means that the movie/show would not only not trigger an initial search, but subsequent RSS matches to that movie/show would be ignored.

### Desired Behavior

The ability to set per-*arr instance whether new movies/shows should be added in a monitored or unmonitored status.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
In Overseerr, monitored == requested, and unmonitored == not requested. However, since Overseerr (currently) does not mark items as not requested or unavailable, you could use the webhook agent to unmonitor items in the *arrs upon approval of requests.

I'm also curious about the use case where you want to submit a request in Overseerr but don't want it to download/search?  Overseerr wasn't designed to work in this way.
