### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by anonyme123** [sct/overseerr#3028]
### Description

Could you implement a download progress bar to replace the spinner? I think you can get the progress from the Signalr feed from Radarr / Sonarr

### Desired Behavior

A download progress bar with an ETA and ideally the speed in Mbps

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by sct** [comment]
This already exists in the manage media slideover.

**Comment by Laiteux** [comment]
Hey! Stumbled upon this issue kinda randomly and I thought I would reply (:

I wanted the same feature around a month ago and figured I would have to make it myself, so I ended up writing a JS script and injecting it for every page load via a nginx `subs_filter` rule, haha. Note that this is considering I am using a snap install, I could probably have edited Overseerr's source and compiled my own build, but didn't bother trying so.

[Here](https://haste.laiteux.dev/frmkpdnm)'s the script if you wanna have a look, and [here](https://haste.laiteux.dev/ieuhttfl) it is as an nginx rule. Please note that I am absolutely not a JS dev, so I'm sorry if some of the code looks messy or not optimal, even though it should be more than fine for the vast majority of it. I have even included some comments I found to be relevant.

![msedge_HItzsswgRg](https://user-images.githubusercontent.com/33204743/191117139-d70a5cfa-7635-4bb8-a3b1-a22e0604b284.gif)
_Don't worry, even though my screenshot shows it in French, the script comes with translations for every language supported by Overseerr (as of v1.29.1 at least)_

Note that you will probably have to install the [subs_filter](https://github.com/yaoweibin/ngx_http_substitutions_filter_module) module yourself, since it doesn't come with nginx by default AFAIK. I remember having to compile my own nginx build in order to include it, but there might be an easier way. Not sure and won't bother helping with that, sorry.

Oh yeah, and the script also replaces the "Requested" badge by a red "Not found" one for medias that were requested more than a minute ago. That made more sense to me and my users, but you can easily remove it if you prefer.

![image](https://user-images.githubusercontent.com/33204743/191118224-33bb2b5b-999b-41a6-9601-67a9ee02db64.png)

By the way, [here](https://smallseotools.com/fr/minify-js/)'s the JS minifier I used to make my script a one-liner, so it would fit as an nginx rule.

Hope it can be of some use to you or someone else as well! In which case, I hope you enjoy (:

**Comment by V-ed** [comment]
> Hey! Stumbled upon this issue kinda randomly and thought I could/would reply (:
> 
> I wanted to have the same feature around a month ago and figured I would have to make it myself, so I ended up writing a JS script and injecting it for every page load via a nginx `subs_filter` rule, haha. Note that this is considering I am using a snap install, I could probably have edited Overseerr's source and compiled my own build, but didn't bother trying so.
> 
> [Here](https://haste.laiteux.dev/ycrtqmou)'s the script if you wanna have a look, and [here](https://haste.laiteux.dev/ieuhttfl) it is as an nginx rule. Please note that I am absolutely not a JS dev, so I'm sorry if some of the code looks messy or not optimal, even though it should be more than fine for the vast majority of it. I have even included some comments I found to be relevant.
> 
> ![msedge_HItzsswgRg](https://user-images.githubusercontent.com/33204743/191117139-d70a5cfa-7635-4bb8-a3b1-a22e0604b284.gif) [ ![msedge_HItzsswgRg](https://user-images.githubusercontent.com/33204743/191117139-d70a5cfa-7635-4bb8-a3b1-a22e0604b284.gif) ](https://user-images.githubusercontent.com/33204743/191117139-d70a5cfa-7635-4bb8-a3b1-a22e0604b284.gif) [ ](https://user-images.githubusercontent.com/33204743/191117139-d70a5cfa-7635-4bb8-a3b1-a22e0604b284.gif) _Don't worry, even though my screenshot shows it in French, the script comes with translations for every language supported by Overseerr (as of v1.29.1 at least)_
> 
> Note that you will probably have to install the [subs_filter](https://github.com/yaoweibin/ngx_http_substitutions_filter_module) module yourself, since it doesn't come with nginx by default AFAIK. I remember having to compile my own nginx build in order to include it, but there might be an easier way. Not sure and won't bother helping with that, sorry.
> 
> Oh yeah, and the script also replaces the "Requested" badge by a red "Not found" one for medias that were requested more than a minute ago. That made more sense to me and my users, but you can easily remove it if you prefer.
> 
> ![image](https://user-images.githubusercontent.com/33204743/191118224-33bb2b5b-999b-41a6-9601-67a9ee02db64.png)
> 
> By the way, [here](https://smallseotools.com/fr/minify-js/)'s one of the few working JS minifiers I used to turn my script into a one-liner, so that it would fit as an nginx rule.
> 
> Please note that I haven't been able to test it yet on v1.30.0 which released just today, but it surely worked perfectly on v1.29.X.
> 
> Hope it can be of some use to you or someone else as well! In which case, I hope you enjoy (:

Looking at the script, it seems solid and I want to try it but I am not a DevOps expert and my nginx configuration does not have the `subs_filter` module, so I'll try to convert it to using `sub_filter` instead, although I'm not sure that this is even something I could do.

I talk about nginx but in reality I simply wanted to confirm that your nginx rule would not work with 1.30.0 as the compiled code you are trying to replace was changed :

![image](https://user-images.githubusercontent.com/16652915/191171403-5805a362-8295-49f9-a599-eefceced8feb.png)

I'm pretty sure the rest however would still work pretty much as you set it up for 1.29.1, but since I couldn't try it myself even in 1.30.0 so far, I can't confirm yet.

I'll try some other stuff to fix my own nginx configuration but wanted to let you know that you'll probably have to at least update it a little for 1.30.0 (at least the nginx rule)!

**Comment by V-ed** [comment]
@Laiteux 

There was actually more changes in 1.30.0 that made your script not work, such as :
- trailing `?manage=1` that screwed up the logic of the `fetchShow` function
- you were getting the `url` from `e.url` but it doesn't seem available? I'm not even sure were that came from, looking at the types of the Badge component there was no url property even in 1.29.1, but if it worked previously it sure doesn't now 😅
- old style for badge

So I updated the script and made an nginx rule that uses the `sub_filter` (which seems to be built-in compared to `subs_filter`? don't quote me on that) and it seems to work so far with my very limited testing!

The fact that I switched to `sub_filter` meant that I no longer has the back reference to the initial regex selector, which means I had to duplicate the previous behavior multiple times in the script. Maybe I could have done a quick function and use that instead. Ah well.

Anyway, here's the nginx rule set that seem to work for me in 1.30.0 :
```
proxy_set_header Accept-Encoding "";
sub_filter 'd.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100"),i&&d.push("hover:bg-indigo-500 bg-opacity-100")' 'if(e.badgeType=="primary"){let url=e.href;let element=getElementByUrl(url);element?.removeAttribute("style");if(e.hasOwnProperty("href")&&url===undefined){const randomIdentifier=Math.random().toString();i.push(randomIdentifier);if(typeof e.children.props.children[1]==="object"){d.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");i&&d.push("hover:bg-indigo-500 bg-opacity-100")};newPromise(async()=>{element=document.getElementsByClassName(randomIdentifier)[0];if(!element)return;url=findUrlFromElement(element);element.setAttribute("href",url);process(url,element,!1)})}else if(url){process(url,element,!0)}else {d.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");i&&d.push("hover:bg-indigo-500 bg-opacity-100")}}else {d.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");i&&d.push("hover:bg-indigo-500 bg-opacity-100")};function process(url,element,isAdmin){if(typeof e.children==="string"||(e.hasOwnProperty("href")&&e.children.props.children[1]===!1)){newPromise(async()=>{element??=getElementByUrl(url);const show=await fetchShow(url);if(Date.now()<Date.parse(show.mediaInfo.updatedAt)+60*1000){element.classList.add(..."$2 $3".split(" "))}else{const globalProps=getGlobalProps();element.classList.add("bg-red-600","!text-red-100",isAdmin?"hover:bg-red-500":null);element.firstChild.firstChild.textContent=(notFoundTranslations[globalProps.locale]??notFoundTranslations.en)+" 😥"}})}else{d.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");i&&d.push("hover:bg-indigo-500 bg-opacity-100");newPromise(async()=>{element??=getElementByUrl(url);const show=await fetchShow(url);let downloads=show.mediaInfo.downloadStatus;const dlPercentsAvg=(downloads=[...new Map(downloads.map(v=>[v.title,v])).values()]).map(dl=>100-dl.sizeLeft/dl.size*100).reduce((p,c)=>p+c,0)/downloads.length/2;element.setAttribute("style",["background: linear-gradient(90deg, rgba(129,140,248,var(--tw-bg-opacity)) "+dlPercentsAvg+"%, rgba(99,102,241,var(--tw-bg-opacity)) 0)","background-size: 200% 200%","animation: progress 2.5s ease"].join(";"));if(document.head.getElementsByTagName("style").length==1){document.head.insertAdjacentHTML("beforeend",["<style>","@keyframes progress {","from { background-position: right }","to { background-position: left }","}","</style>"].join("\\n"))}})}}function newPromise(func,delay=100){return new Promise(_=>sleep(delay).then(func))}async function sleep(milliseconds){return new Promise(resolve=>setTimeout(resolve,milliseconds))}function getGlobalProps(){return JSON.parse(document.getElementById("__NEXT_DATA__").textContent).props}function getElementByUrl(url){return document.querySelector(`[href="` + url + `"]`)}function findUrlFromElement(element){switch(window.location.pathname){case"/":case"/requests":return element.parentElement.parentElement.parentElement.querySelector(`a[href^="/movie/"],a[href^="/tv/"]`).href;default:return window.location.href}}async function fetchShow(url){const urlSplit=url.replace(/\?.*/, "").split("/");let showType=urlSplit[urlSplit.length-2];if(showType=="series")showType="tv";if(showType=="tv")url=findUrlFromElement(getElementByUrl(url));const showId=url.replace(/\?.*/, "").split("/").pop();return await fetch("/api/v1/"+showType+"/"+showId).then(show=>show.json())}const notFoundTranslations={"ca":"No trobat","cs":"Nenalezeno","da":"Ikke fundet","de":"Nicht gefunden","en":"Not found","es":"No se ha encontrado","fr":"Non trouvé","it":"Non trovato","hu":"Nem található","nl":"Niet gevonden","nb-NO":"Ikke funnet","pl":"Nie znaleziono","pt-BR":"Não encontrado","pt-PT":"Não encontrado","sv":"Hittades inte","el":"Δεν βρέθηκε","ru":"Не найден","sr":"Није пронађен","ja":"見つかりません","zh-TW":"未找到","zh-CN":"未找到"};const downloadingTranslations={"en":"Downloading","es":"Downloading","fr":"Téléchargement"};';
sub_filter 'u.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100"),o&&u.push("hover:bg-indigo-500 bg-opacity-100")' 'if(e.badgeType=="primary"){let url=e.href;let element=getElementByUrl(url);element?.removeAttribute("style");if(e.hasOwnProperty("href")&&url===undefined){const randomIdentifier=Math.random().toString();i.push(randomIdentifier);if(typeof e.children.props.children[1]==="object"){u.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");o&&u.push("hover:bg-indigo-500 bg-opacity-100")};newPromise(async()=>{element=document.getElementsByClassName(randomIdentifier)[0];if(!element)return;url=findUrlFromElement(element);element.setAttribute("href",url);process(url,element,!1)})}else if(url){process(url,element,!0)}else {u.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");o&&u.push("hover:bg-indigo-500 bg-opacity-100")}}else {u.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");o&&u.push("hover:bg-indigo-500 bg-opacity-100")};function process(url,element,isAdmin){if(typeof e.children==="string"||(e.hasOwnProperty("href")&&e.children.props.children[1]===!1)){newPromise(async()=>{element??=getElementByUrl(url);const show=await fetchShow(url);if(Date.now()<Date.parse(show.mediaInfo.updatedAt)+60*1000){element.classList.add(..."$2 $3".split(" "))}else{const globalProps=getGlobalProps();element.classList.add("bg-red-600","!text-red-100",isAdmin?"hover:bg-red-500":null);element.firstChild.firstChild.textContent=(notFoundTranslations[globalProps.locale]??notFoundTranslations.en)+" 😥"}})}else{u.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");o&&u.push("hover:bg-indigo-500 bg-opacity-100");newPromise(async()=>{element??=getElementByUrl(url);const show=await fetchShow(url);let downloads=show.mediaInfo.downloadStatus;const dlPercentsAvg=(downloads=[...new Map(downloads.map(v=>[v.title,v])).values()]).map(dl=>100-dl.sizeLeft/dl.size*100).reduce((p,c)=>p+c,0)/downloads.length/2;element.setAttribute("style",["background: linear-gradient(90deg, rgba(129,140,248,var(--tw-bg-opacity)) "+dlPercentsAvg+"%, rgba(99,102,241,var(--tw-bg-opacity)) 0)","background-size: 200% 200%","animation: progress 2.5s ease"].join(";"));if(document.head.getElementsByTagName("style").length==1){document.head.insertAdjacentHTML("beforeend",["<style>","@keyframes progress {","from { background-position: right }","to { background-position: left }","}","</style>"].join("\\n"))}})}}function newPromise(func,delay=100){return new Promise(_=>sleep(delay).then(func))}async function sleep(milliseconds){return new Promise(resolve=>setTimeout(resolve,milliseconds))}function getGlobalProps(){return JSON.parse(document.getElementById("__NEXT_DATA__").textContent).props}function getElementByUrl(url){return document.querySelector(`[href="` + url + `"]`)}function findUrlFromElement(element){switch(window.location.pathname){case"/":case"/requests":return element.parentElement.parentElement.parentElement.querySelector(`a[href^="/movie/"],a[href^="/tv/"]`).href;default:return window.location.href}}async function fetchShow(url){const urlSplit=url.replace(/\?.*/, "").split("/");let showType=urlSplit[urlSplit.length-2];if(showType=="series")showType="tv";if(showType=="tv")url=findUrlFromElement(getElementByUrl(url));const showId=url.replace(/\?.*/, "").split("/").pop();return await fetch("/api/v1/"+showType+"/"+showId).then(show=>show.json())}const notFoundTranslations={"ca":"No trobat","cs":"Nenalezeno","da":"Ikke fundet","de":"Nicht gefunden","en":"Not found","es":"No se ha encontrado","fr":"Non trouvé","it":"Non trovato","hu":"Nem található","nl":"Niet gevonden","nb-NO":"Ikke funnet","pl":"Nie znaleziono","pt-BR":"Não encontrado","pt-PT":"Não encontrado","sv":"Hittades inte","el":"Δεν βρέθηκε","ru":"Не найден","sr":"Није пронађен","ja":"見つかりません","zh-TW":"未找到","zh-CN":"未找到"};const downloadingTranslations={"en":"Downloading","es":"Downloading","fr":"Téléchargement"};';
sub_filter 'c.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100"),l&&c.push("hover:bg-indigo-500 bg-opacity-100")' 'if(e.badgeType=="primary"){let url=e.href;let element=getElementByUrl(url);element?.removeAttribute("style");if(e.hasOwnProperty("href")&&url===undefined){const randomIdentifier=Math.random().toString();i.push(randomIdentifier);if(typeof e.children.props.children[1]==="object"){c.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");l&&c.push("hover:bg-indigo-500 bg-opacity-100")};newPromise(async()=>{element=document.getElementsByClassName(randomIdentifier)[0];if(!element)return;url=findUrlFromElement(element);element.setAttribute("href",url);process(url,element,!1)})}else if(url){process(url,element,!0)}else {c.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");l&&c.push("hover:bg-indigo-500 bg-opacity-100")}}else {c.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");l&&c.push("hover:bg-indigo-500 bg-opacity-100")};function process(url,element,isAdmin){if(typeof e.children==="string"||(e.hasOwnProperty("href")&&e.children.props.children[1]===!1)){newPromise(async()=>{element??=getElementByUrl(url);const show=await fetchShow(url);if(Date.now()<Date.parse(show.mediaInfo.updatedAt)+60*1000){element.classList.add(..."$2 $3".split(" "))}else{const globalProps=getGlobalProps();element.classList.add("bg-red-600","!text-red-100",isAdmin?"hover:bg-red-500":null);element.firstChild.firstChild.textContent=(notFoundTranslations[globalProps.locale]??notFoundTranslations.en)+" 😥"}})}else{c.push("bg-indigo-500 bg-opacity-80 border border-indigo-500 !text-indigo-100");l&&c.push("hover:bg-indigo-500 bg-opacity-100");newPromise(async()=>{element??=getElementByUrl(url);const show=await fetchShow(url);let downloads=show.mediaInfo.downloadStatus;const dlPercentsAvg=(downloads=[...new Map(downloads.map(v=>[v.title,v])).values()]).map(dl=>100-dl.sizeLeft/dl.size*100).reduce((p,c)=>p+c,0)/downloads.length/2;element.setAttribute("style",["background: linear-gradient(90deg, rgba(129,140,248,var(--tw-bg-opacity)) "+dlPercentsAvg+"%, rgba(99,102,241,var(--tw-bg-opacity)) 0)","background-size: 200% 200%","animation: progress 2.5s ease"].join(";"));if(document.head.getElementsByTagName("style").length==1){document.head.insertAdjacentHTML("beforeend",["<style>","@keyframes progress {","from { background-position: right }","to { background-position: left }","}","</style>"].join("\\n"))}})}}function newPromise(func,delay=100){return new Promise(_=>sleep(delay).then(func))}async function sleep(milliseconds){return new Promise(resolve=>setTimeout(resolve,milliseconds))}function getGlobalProps(){return JSON.parse(document.getElementById("__NEXT_DATA__").textContent).props}function getElementByUrl(url){return document.querySelector(`[href="` + url + `"]`)}function findUrlFromElement(element){switch(window.location.pathname){case"/":case"/requests":return element.parentElement.parentElement.parentElement.querySelector(`a[href^="/movie/"],a[href^="/tv/"]`).href;default:return window.location.href}}async function fetchShow(url){const urlSplit=url.replace(/\?.*/, "").split("/");let showType=urlSplit[urlSplit.length-2];if(showType=="series")showType="tv";if(showType=="tv")url=findUrlFromElement(getElementByUrl(url));const showId=url.replace(/\?.*/, "").split("/").pop();return await fetch("/api/v1/"+showType+"/"+showId).then(show=>show.json())}const notFoundTranslations={"ca":"No trobat","cs":"Nenalezeno","da":"Ikke fundet","de":"Nicht gefunden","en":"Not found","es":"No se ha encontrado","fr":"Non trouvé","it":"Non trovato","hu":"Nem található","nl":"Niet gevonden","nb-NO":"Ikke funnet","pl":"Nie znaleziono","pt-BR":"Não encontrado","pt-PT":"Não encontrado","sv":"Hittades inte","el":"Δεν βρέθηκε","ru":"Не найден","sr":"Није пронађен","ja":"見つかりません","zh-TW":"未找到","zh-CN":"未找到"};const downloadingTranslations={"en":"Downloading","es":"Downloading","fr":"Téléchargement"};';
sub_filter_once off;
sub_filter_types *;
```

Please be aware that I have no idea what I'm doing with nginx so there is more than probably a better way to do it than what I did above!

There seemed to have multiple instances where the Badge was being set, which meant (again with the lack of regex support in the `sub_filter` rule) that I had to duplicate the whole rule for the few variables that changed in the compiled React code.

With my particular setup, the `sub_filter` rule was also getting past the limits of characters, so I had to remove all of the unused `downloadingTranslations` that were all in english anyway. This would be an optimization point that I haven't tried to look into yet. (Probably by creating a small function to get the initial behavior as I said I duplicated it multiple times, and/or doing a full minimization instead of only stripping whitespace? eh, many possibilities, not enough sleep)

I haven't "un-minified" the script yet, but it's 2 and an half in the morning and I kind of need some sleep, so I'll leave that part for later.

I'll update here if need be, thanks for the nice script and for the nginx rule that did actually help a non-devops guy in the end!

**Comment by sct** [comment]
I imagine you all know, but it needs to be said anyways. We will not offer any support for your Overseerr instance breaking if you are injecting third-party JavaScript into the application. It can break at any time and without notice. I do not recommend using something like this.

Better just to open a PR directly if you want to see this functionality or wait for us to add it.

**Comment by Laiteux** [comment]
@V-ed Hey!

First of all I was wondering if you spoke French too? Because your name sounds French (:

Secondly, thank you! I wasn't aware of how v1.30.0 was breaking the script!

Here's every fix summed up, thanks to your work:

- `e.url` isn't available anymore (I swear it used to be hahah), so `e.href` had to be used instead
- `?manage=1` new query parameter in the button URL (.href) was breaking the API request
- There now seem to be multiple, differently minified JS chunks we have to replace (inject in)
- The RegEx therefore had to change, plus new classes were added to the button with v1.30.0 which had to be added anyway

One small thing I also had to mention: You forgot to replace these two RegEx capture groups in your `sub_filter` script. Considering it was 2 AM, I can relate 😜 

![Code_BHwgvafjKl](https://user-images.githubusercontent.com/33204743/191268828-f2c9337d-1757-4d39-b445-59b26469b8c2.jpg)

I have edited my original post in order to reflect these fixes (keep in mind I'm still using `subs_filter` with a new RegEx there).

Here are a few new issues that seem to have showed up with v1.30.0, though, and which I don't really have the motivation to fix right now:

- There used to be a cool 2.5s long animation on the progress bar (which you can see as a GIF on my original post), and it does not seem to be there anymore. For me, it only works on the first CTRL+F5 I do (which re-fetches all the JS scripts), but if I do F5 to refresh the page after then it's not there anymore. The progress bar is, but the animation is gone. Too sad, it looked cool.
- The hovering is a little broken, or at least looks a little messy. See the GIF below.
- The script is sending way too many API requests to fetch the show (can be tested by hovering), not sure why and can't recall it did that before v1.30.0. See the same GIF below.

![msedge_qZmqmTNVXk](https://user-images.githubusercontent.com/33204743/191270032-a0968549-271a-4e26-9107-7e3c18dd598a.gif)

If you want to talk more about all of this and/or maybe work on some quick fixes together, we can move to Telegram if you have it: https://t.me/Matty - Otherwise, I have Discord as well, even though I use it way less: `Laiteux#1337`

**Comment by Laiteux** [comment]
One last thing: I'd like to mention that, as @sct said himself, this should be a PR. However, as I already said I am not a JS dev at all (so even less a React dev, I do C#) and I would be too worried of breaking/doing stuff wrong. Maybe one day I will be turning this whole thing into a PR, but for now I'd like to keep it as a (not-so-)messy sideloaded script, for various different reasons. Well, unless someone wants to rewrite it all, I guess? For now, maybe a quick GitHub repo with proper instructions on how to set this up could be made, but I think that's it.

**Comment by anonyme123** [comment]
@Laiteux that's too bad, this looks awesome and exactly what I wanted. 

@sct does that mean you'll consider this as a future feature? If so, can you reopen this issue?

**Comment by sct** [comment]
> @Laiteux that's too bad, this looks awesome and exactly what I wanted.
> 
> @sct does that mean you'll consider this as a future feature? If so, can you reopen this issue?

There is already an open feature request: https://github.com/sct/overseerr/issues/994

**Comment by V-ed** [comment]
> Here are a few new issues that seem to have showed up with v1.30.0, though, and which I don't really have the motivation to fix right now:
> 
> * There used to be a cool 2.5s long animation on the progress bar (which you can see as a GIF on my original post), and it does not seem to be there anymore. For me, it only works on the first CTRL+F5 I do (which re-fetches all the JS scripts), but if I do F5 to refresh the page after then it's not there anymore. The progress bar is, but the animation is gone. Too sad, it looked cool and took me a while hahah.
> * The hovering is a little broken, or at least looks a little messy. See the GIF below.
> * The script is sending way too many API requests to fetch the show (can be tested by hovering), not sure why and can't recall it did that before v1.30.0. See the same GIF below.
> 
> Regarding the animation btw, I noticed that there were now two `<style>` tags (instead of just 1 before) in the `<head>`, so I switched to a more proper check instead of just `.length == 1`.
> 
> ![msedge_qZmqmTNVXk](https://user-images.githubusercontent.com/33204743/191270032-a0968549-271a-4e26-9107-7e3c18dd598a.gif) [ ![msedge_qZmqmTNVXk](https://user-images.githubusercontent.com/33204743/191270032-a0968549-271a-4e26-9107-7e3c18dd598a.gif) ](https://user-images.githubusercontent.com/33204743/191270032-a0968549-271a-4e26-9107-7e3c18dd598a.gif) [ ](https://user-images.githubusercontent.com/33204743/191270032-a0968549-271a-4e26-9107-7e3c18dd598a.gif)
> 
> If you want to talk more about all of this and/or maybe work on some quick fixes together, we can move to Telegram if you have it: [t.me/Matty](https://t.me/Matty) - Otherwise, I have Discord as well, even though I use it way less: `Laiteux#1337`

@Laiteux I did see some issues too, and for some reason it doesn't seem to work on Android Edge, but eh, it's still nice that it works in the way it currently does.

And yes, my main language is also French! But I'm not french, or should I say I'm french Canadian (sorry) haha

I would indeed like to talk about more fixes to this script, I love discussing potential fixes and issues in nice programs, and until this is made official into Overseerr, I see great value added by injecting this script to my users - them being able to see the prgress will stop many times where I get the question "did you find this show?" - but I don't need to say that, you already know the value of such feature haha

I don't use telegram (it's really not used at all in Canada, or at least in Quebec) and you seem to have disabled Discord friend requests - you'd need to add me if we keep this going in Discord : `V-ed#5131`. Hopefully the timezone difference won't be too much of an issue haha

**Comment by Laiteux** [comment]
Added you on Discord! Btw, just 2 minutes before you posted your comment, I had edited mine to remove the first issue that was listed (regarding the broken animation), because for some reason it now seems to work just fine for me.

**Comment by anthonywde** [comment]
Hello, is it possible to create a short guide for installing your script?

**Comment by V-ed** [comment]
> Hello, is it possible to create a short guide for installing your script?

The thread about injecting scripts modifications via nginx rules is rendered obsolete as Overseer now has native functionality to display download progress, almost exactly as what @Laiteux did.

Simply use a recent version and you should have it!

**Comment by anthonywde** [comment]
Also jelly?

**Comment by V-ed** [comment]
Not sure what you mean by this question, this is the Github repo of Overseerr, not Jellyfin nor Plex.

If you are referring to the https://github.com/Fallenbagel/jellyseerr fork, then go create an issue over there if it doesn't work.

**Comment by toniopelo** [comment]
For those who would end up here, not understanding why they don't see the progress even with the latest version of overseer, you probably need to enable scans under Settings > Applications > Sonarr/Radarr

**Comment by Laiteux** [comment]
#- [x] k- [ ]ô l loôôokookiookoôoôôooôôooôokookokoo  ok o o o o okoko okoo  ookkk oo oo oo o okkoook nlkokkko ko okok kk o o oko o ok   o k  oko k o k p l p l p l' l pl' lplo lo
 l o oo  k  ok k o okko  o  k o kk oko
