### ISSUE TITLE
User setting to Override Service Specific Quality Profile

### ISSUE THREAD

**Issue by espentruls** [sct/overseerr#3029]
### Description

I have a high quality profile and a streaming optimized profile on standard radarr. I have set the high quality as standard, but a couple of people who use my service has a slow internet connection, so it would be a good addition to Overseerr to include an override option in the users settings. I know I can give them advanced request permission but they are not tech savvy so they don't understand it. 

### Desired Behavior

Per user, in user settings an option like the "Override Global Limit" to be able to choose Override Service Specific Quality Profile per service instance what profile it should default to for that user. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
I believe #1459 would allow you to add another Radarr/Sonarr server that your users can choose from if they want the default (high quality profile) or the streaming optimized profile.
How does that sound?

**Comment by espentruls** [comment]
> I believe #1459 would allow you to add another Radarr/Sonarr server that your users can choose from if they want the default (high quality profile) or the streaming optimized profile. How does that sound?

No I have one Radarr instance with multiple quality profiles, so this wouldn't work. You should be able to just override the default quality profile per user. In reality you could do it with every setting for every service instance and just hide it all under a advanced settings tab on the user settings page.

**Comment by V-ed** [comment]
While cumbersome, @danshilm's suggestion is still a valid workaround until this feature (which I would like so much, especially for languages) is implemented.

Even if it's counter-intuitive, you can add another Radarr instance that points to the same server but you set it to use another quality profile in the options.

In the example below, I have two "Radarr Server" pointing to my only instance but with a different quality preset selected so that one of my user has the ability to request content that is in french.
![image](https://user-images.githubusercontent.com/16652915/191056261-6843de44-18d3-4d7e-ae95-adea2f937000.png)

The unfortunate thing here is that I have to manually change this user's request when accepting it, which means it probably won't work when auto-approving if that is one of the use case you wanted it for.

Until then, you should probably follow https://github.com/sct/overseerr/issues/609 as your issue is pretty much a duplicate of this one!

**Comment by slinkoff** [comment]
def +1 from me
I have 2 profiles setup with high quality and streaming profiles attached. I set the default to streaming as nearly all users are remote and then I have admin (me) able to select a profile so when I request something for myself/family I can override it to be high quality. It works fine but its extra steps and we all like it when automation removes steps so being able to assign servers/quality profiles to users would be better. Ombi does this.
