### ISSUE TITLE
Separate auto search for anime tv shows on the same instance

### ISSUE THREAD

**Issue by Xarishark** [sct/overseerr#3047]
### Description

Enable a second checkbox ( or a settings to separate) for auto search on anime serries.

### Desired Behavior

When settings up a sonnar instance have a separate box for the user to choose if he want sonnar to auto-search for anime or not. This way people that are requesting an old anime or whole series can still request it and notify me to download it manually through overseerr

### Additional Context

Its known that automated anime downloads are super hard when it comes to whole series downloads as almost nobody follows the scene rules 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by jojolll** [comment]
In the same vein, I have many series indicated as "Anime" by TVDB that download much better when Sonarr searches for them as "Standard" (ex : series with complete seasons releases like My Hero Acadamia, or Fullmetal Alchemist). 

Having a parameter to override the type returned by TVDB could be very interesting. Instead of searching the 64 episodes of FMA one by one and finding nothing with the type "Anime" Sonarr could find the whole season in one search if it is available. 
Here is the Sonarr doc talking about this : 

![image](https://user-images.githubusercontent.com/26553241/192117499-25b46f6b-ec0b-4168-a557-eb01d31ef01a.png)
