### ISSUE TITLE
PGP encrypted message inline in email body

### ISSUE THREAD

**Issue by strausmann** [sct/overseerr#3050]
### Description

Currently, for a PGP signed email, the message is attached to the email as an attachment. But with this the PGP encrypted message is not decryptable with Mailvelope.

![image](https://user-images.githubusercontent.com/4519228/192220457-8f39bf69-1ca1-403a-b999-00de4b73785b.png)

### Desired Behavior

The user should be able to choose how the encrypted message is sent via email in addition to his public key.

Option A: View the current status, the message will be attached to the email as *.asc file.

Option B: The message is not attached but written as text in the email body. See the screenshot in the description as an example.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ankarhem** [comment]
Hey, I don't think this is something that we would like to implement.

As I understand the PGP inline format is not a standard format, and has two main issues. One being that it can't prove the message integrity, and the other being that it will break for non-ascii characters.

Disregarding the first problem, we can understand that we would need to opt out of html message templates in order to support inline pgp.
