### ISSUE TITLE
Auto-match language based on content

### ISSUE THREAD

**Issue by nn22954** [sct/overseerr#3214]
### Description

When requesting a TV show using radarr the default is any language. When searching the original language is shown.
If the original language could be selected in the dropdown by default that would be great. In some countries dubbing is the norm, and users may want their native tongue to be default. This could then be a setting per user, and globally.
Global setting could have the list of available languages from radarr, and allow overriding globally and per user.

### Desired Behavior

Allow to set default desired language globally and per user based on profiles in radarr.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by danshilm** [comment]
Language profiles are being removed in Sonarr v4 and the way to set the preferred language is to use quality profiles. The dropdown you're referring to was present a while ago, but it was hidden since.

For automatically selecting a specific Radarr instance for a specific language, the [request routing feature](https://github.com/sct/overseerr/issues/1881) would allow you to do that. So I'll close this issue in favour of that one. Subscribe to that issue for updates.
