### ISSUE TITLE
Allow Overseerr to change the download priority level

### ISSUE THREAD

**Issue by macj72x** [sct/overseerr#3342]
### Description

Users may have several downloads queued from something such as lists or other automated methods, but manual movie requests from Overseerr should have the ability to have a higher priority level over the automated downloads. This priority level could be put in from the front end at the user request screen or an admin setting

### Desired Behavior

Preferred behavior would be for the user to request media then Overseerr applies a high priority (or something else of the admins choice) that is then pushed to sonarr or radarr to be downloaded before other automated downloads

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
Overseerr doesn't connect to or interact with your download clients in any way, so it'd be up to Sonarr/Radarr to implement this.

Overseerr supports Sonarr/Radarr tags already that could facilitate identifying requested media if Sonarr/Radarr were to implement this feature.

**Comment by paulo-erichsen** [comment]
here's a way to solve this without any code changes, just configuration changes

1. on radarr, create an "overseerr" tag 
2. on overseerr, under settings > services > radarr, make sure that radarr requests have the "overseerr" tag 
3. back to radarr, under settings > download clients, change your default download client to be priority 2 instead of 1
4. while at download clients, add another download client that's the same settings from your default. Basically copy everything including host, port, password, except the following that's different 
  a. name: qBittorrent (overseer) ---> original name was just "qBittorrent" so I just added overseer to make it easy to identify 
  b. priority: 1
  c. recent priority: first 
  d. older priority: first
  e. initial state: start 
  f. tags: overseerr 

This works with with qbittorrent and possibly other download clients. Configuring this way makes is such that whenever something is added through overseerr, it goes to the top of the download client list and is started right away
