### ISSUE TITLE
Add the ability to create local users for sign-in.

### ISSUE THREAD

**Issue by TheChrisK** [sct/overseerr#335]
**Is your feature request related to a problem? Please describe.**
Currently only users with a Plex account can sign into Overseerr.

**Describe the solution you'd like**
Add the ability to create local users for sign in where the same permissions can be assigned. This would be mostly for local users. In this context, my wife obviously enjoys Plex but doesn't have her own account and my server creds are too complex to expect her to remember.

**Describe alternatives you've considered**
Local users have to ask the server owner to request a title which defeats the purpose for those without a Plex account. With Ombi, my wife can log in with her own credentials and request titles.

**Additional context**
None

**Comment by costaht** [comment]
I'm adding the text of another ticket (#497) I had opened before finding this one here:

Is your feature request related to a problem? Please describe.
I have Plex Pass with some "Home users", so they can use Plex Pass features. These users don't have e-mail attached to them and the fact that only the admin user and "Friends" (users with e-mails) are imported is frustrating because my most important users can't benefit from Overseerr.

Describe the solution you'd like
I want to be able to import my "Home Users" or manually create them and set a password that they can change later. I could also add an e-mail to their profile later in case I want to use e-mail notifications, or their Telegram ID or username for the day Telegram notification is available.

Describe alternatives you've considered
I have no alternatives. If I give them access to Plex as "Friends" they will lose their Plex Pass features (hw transcoding, trailers, etc..)
Thank you!

**Comment by sct** [comment]
> I'm adding the text of another ticket (#497) I had opened before finding this one here:
> 
> 
> 
> Is your feature request related to a problem? Please describe.
> 
> I have Plex Pass with some "Home users", so they can use Plex Pass features. These users don't have e-mail attached to them and the fact that only the admin user and "Friends" (users with e-mails) are imported is frustrating because my most important users can't benefit from Overseerr.
> 
> 
> 
> Describe the solution you'd like
> 
> I want to be able to import my "Home Users" or manually create them and set a password that they can change later. I could also add an e-mail to their profile later in case I want to use e-mail notifications, or their Telegram ID or username for the day Telegram notification is available.
> 
> 
> 
> Describe alternatives you've considered
> 
> I have no alternatives. If I give them access to Plex as "Friends" they will lose their Plex Pass features (hw transcoding, trailers, etc..)
> 
> Thank you!

Local accounts will eventually make their way in. But as for one of your issues... I may be mistaken but I believe if you have your other home users make their own plex accounts and then you add them as "home users" they will still get your plex pass shared to them. Plus, they can log into Overseerr then and you won't have to share your admin account information.

**Comment by modem7** [comment]
If I could make a slight addendum to whenever this feature gets implemented: 

Please could we have the ability to disable local logins and only allow Plex logins (exactly like current behaviour)? This should increase security, especially in the case of things like brute force attacks.

**Comment by costaht** [comment]
> If I could make a slight addendum to whenever this feature gets implemented:
> 
> Please could we have the ability to disable local logins and only allow Plex logins (exactly like current behaviour)? This should increase security, especially in the case of things like brute force attacks.

Just don't create local users ;)

**Comment by modem7** [comment]
Cool, if that's the simple solution, then even better!

Was concerned that it'd be like Tautulli or Ombi where the admin user also
has a local login.

Thanks!

**Comment by costaht** [comment]
Since you need to login with your Plex account in order to import your
users from Plex, I believe the majority of admins will use their Plex
account, not a local admin. This demand is a solution for those who don't
have a Plex account (Home Users).

**Comment by ankarhem** [comment]
Can you assign me to this? Thanks 😄 @samwiseg0
