### ISSUE TITLE
Treat requests as available if all requested seasons are available.

### ISSUE THREAD

**Issue by Alexays** [sct/overseerr#3366]
### Description

Hi!
At the moment, if I filter the requests on unavailable, I also see the series that have all the requested seasons available instead of seeing those that don't have all the seasons available.
Thanks!

### Desired Behavior

I would like to see season requests for series if they are all available, treated as available and not partially available.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by slinkoff** [comment]
I think this is the same request I have. If a user requests a season of a show, they should receive a notification when all episodes of that season are available but because it's flagged as "partially available" they don't. Status of season could be partially available when some episodes of a season are downloaded but not all of them. Status of "available" could/should apply at the season level when all episodes of the season are there and not at the entire show level.

**Comment by ilmtr** [comment]
This is also an issue for me.

When you filter your requests on _Processing/Unavailable_ it shows specific season requests, for example 2 seasons, but the status of this request is "Partially evailable", even though all 2 requested seasons are available. 

In my requests overview most "Unavaible" requests are actually available.  I'm suprised that not more users find this also unintuitive.
