### ISSUE TITLE
Manually change destination paths/quality profiles of requests

### ISSUE THREAD

**Issue by mikeyvt** [sct/overseerr#351]
**Is your feature request related to a problem? Please describe.**
Currently you are only able to choose 1 'root' folder when setting up Overseerr.  I have some categorized folders for certain videos.  Having it all sent to the root folder, I then have to manually move it once it's all grabbed, then go to Radarr/Sonarr respectively to change paths

**Describe the solution you'd like**
Would be nice if I can manually set the paths either by using the paths seen in Radarr/Sonarr when I approve the requests or manually entering them.  Given that Overseerr can connect to Radarr/Sonarr and see it's paths it would be great if that can just be rolled over.

**Describe alternatives you've considered**
N/A

**Additional context**
This is somewhat similar to Issue #266 with creating separate folders but going 1 step further in being able to change the folder path in the 'request' approval area.

**Comment by bobokun** [comment]
I agree to this! Would be a very nice feature to have :)

**Comment by kaiguy** [comment]
Agree! Would love to see this!

**Comment by burtaverde** [comment]
would be great if it was possible to have "default" folders depending on the user that way you only set it up once.

**Comment by CobblerSalad** [comment]
Yes, this is a needed feature for me. I get lots of requests for Kids movies and regular movies equally and being able to set the root folder per request is great.

**Comment by EvilTactician** [comment]
This feature is the only thing holding me back from being able to jump ship.

I love Overseerr's interface and the way it syncs the libraries, it's done so well. However, I have my libraries split between Movies and Animated Movies, and for TV between Anime, TV, Non-Fiction and Animated.

Right now if someone asks for a show that falls in Non-Fiction or Animated, it ends up in the main TV library, which becomes really messy to deal with. Because Overseerr also auto-searches on top of this (doesn't have the option to only add to radarr/sonarr and NOT search right away), there's no way to manually intervene in time.

**Proposed Solution**
Overseerr already picks up our Libraries from Plex so it would be awesome if it allows us to pick the following for each:

- root profile
- quality profile
- language profile (sonarr v3, for anime many people use Japanese audio)
- release profile (sonarr v3, adds a tag further refining searches, very useful!)

The latter two would be optional.

Upon requesting a series or movie, the user could be prompted to select the correct library (this is needed to cover cases which have auto-approve on) - and upon approving, the admin could change this, ensuring all the correct profiles are passed to sonarr/radarr. This would make Overseerr very robust, whatever library set-up people might be using.

**Comment by tigervol** [comment]
Hello,

I know this is in the "planned" section but I just wanted to comment and add my vote for this feature! It would be great if I could map categories with quality profiles and send them to specific folder paths based on a drop-down menu in Overseerr, and manage access to each category on a by-user level.

Thanks for all your work on this!

**Comment by mikeyvt** [comment]
> Already see the issue closed and in the planned stage but wanted to add my +1 for this feature but wanted to make sure that the option for different libraries were available during the approve screen and not presented to the end user. I don't want my users to dictate where the content goes in what library. Similar to previous request software, on a given request the owner can change the default folder and quality profile before approving. This would be the ideal solution. IMO.
> 
> Props for coming a long way in such a short time for a project that's still in alpha. Thanks and Happy New Year.

Yeah I never meant for this to be on the end user side.  Just the owner/approver side.

**Comment by henningBunk** [comment]
I created a similar  issue because I didn't find this one before: https://github.com/sct/overseerr/issues/606 There I wrote:

> The user can decide a root path before the request is send.
It would be great to give the root paths friendly names which are displayed to the user:
/array/media/video/movies -> Movies

For me this this would be important since I have auto approve for all my users so the users have to chose the destination. So maybe one could boil it down to: The approver selects the root path. When auto approve is activated the approver is the user.

**Comment by After-Shock** [comment]
Wouldn't that be on you as the server owner to create the friendly names.  I don't want my users requesting Showgirls and putting it in until Kids Movie section. Maybe that's just me.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by henningBunk** [comment]
Yes definetly! That would be something for the configuration. Than when a user requests something he/she can select the path e.g. 'Movie' or 'Documentary'.
