### ISSUE TITLE
Sort requests by title

### ISSUE THREAD

**Issue by martinjgrunwald** [sct/overseerr#3576]
### Description

At the moment you can only sort requests by "most recent" and "last modified"

### Desired Behavior

I would like to be able to sort requests by movie/show title

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by EtzBetz** [comment]
As I would like to have more sorting options, I looked whether I could do this myself. Codebase looks manageable to me, I'll try to add this and a few other sorting options.


I'll still need to figure out how to correctly handle movies/series without release date, as I personally would like them hidden/at the end, but this is a sort, not a filter, and putting them at the end would add quirky behavior when toggling ascending/descending.

**Comment by EtzBetz** [comment]
I'm facing an issue [here](https://github.com/sct/overseerr/blob/107bce2e86c4c4cef26d22b6d72b6ea56e2df9c3/server/routes/request.ts#L94), this would be the place to add the sorting filter on the actual server's side. The problem here is, that the title seems to be defined differently for [movies](https://github.com/sct/overseerr/blob/107bce2e86c4c4cef26d22b6d72b6ea56e2df9c3/server/api/themoviedb/interfaces.ts#L16) and [series](https://github.com/sct/overseerr/blob/107bce2e86c4c4cef26d22b6d72b6ea56e2df9c3/server/api/themoviedb/interfaces.ts#L25).
So I need to have a different property to sort for between movies and series. (I am not completely sure whether `TmdbTvResult` actually is the correct typedef for a series?)

Is there any easy fix for this, or does this mean we have to hack in some more manual code? I guess this is not the first place where this is being run into?

**Comment by danshilm** [comment]
This is not possible since we don't store the request's media title, and changing that would require a pretty good amount of changes across Overseerr's backend and frontend alike. Not very much worth it imo.
We actually came across the issue that we don't store titles when we were trying to show more information about content that was already requested but was already deleted from TMDB since the information we currently store isn't really that useful for users.

To note: the fields that can be used to sort the requests are [these](https://github.com/sct/overseerr/blob/develop/server/entity/MediaRequest.ts#L370-L461) and [these](https://github.com/sct/overseerr/blob/develop/server/entity/Media.ts#L69-L139)
