### ISSUE TITLE
Notify when all released episodes are available or partial availability

### ISSUE THREAD

**Issue by clifford64** [sct/overseerr#3578]
### Description

Currently, Overseerr will not send a notification until all episodes of a show are available. If a show has 3 seasons and only season 1 and 2 have been released and acquired so far, then it will not send a notification if the show was recently requested. This is because it sees that Season 3 is not available yet because it hasn't been released yet.

### Desired Behavior

Having the option to send notifications based on episodes that are partially available or seasons that are available or per episode would be helpful. Or something that is single notification per show or per season. 

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by clifford64** [comment]
Issue originally brought up in #2690 but nothing was done and it was auto closed. I would like to bring it back up.

**Comment by nmbrg** [comment]
It’s insane that there’s no option to get a notification on first episode of a season only. Me and every person I’ve talked to want only this type of notification for TV-series. We do not care for notifications when the whole season is available, only for when the first episode is available so we get a heads up that the tv-series have a new season started. After that it’s pretty common to know which day the next episode is available to watch without getting notifications.

**Comment by OwsleyJr** [comment]
Individual episode support needs to be added. Closing in favor of #342.

**Comment by nmbrg** [comment]
> Individual episode support needs to be added. Closing in favor of #342.

I fail to see the reason why this is closed. Afaik the issue you’re referring to are about the ability to request individual episodes. This issue are about the ability the get notifications either on every episode or at first episode on every season, instead of as it is now, getting a notification when the last episode of a season is available. If I haven’t misunderstood this issue it has nothing to do about the ability to request stuff in a particular way.

**Comment by slinkoff** [comment]
agree - new show, first few episodes have downloaded but no notification because it won't be seen as available as a season until the last episode is acquired. Clearly we want to be notified when the season starts or as each new episode is downloaded.

Air date appears to be available info in Overseer. Logic check could be to check if air date is within x amount of days of current date. i.e., it's a newly aired episode of the show. If so, send notification for partially available show/new episode. Optionally only send notification if it's the first episode of the season.
