### ISSUE TITLE
requests backed up to a file hourly + skip the forced option to use plex

### ISSUE THREAD

**Issue by megasyntax** [sct/overseerr#3609]
### Description

I'm frustrated that when my container no longer works I reset and my requests are all gone, r**ead the desired behaviour part.**

My workflow so to speak is Infuse and cloud storage but both Sonarr and Radarr are bad for cloud use and it's a myriad of problems for me.

### Desired Behavior

I prefer this application to keep track of requests made by saving them to a location on my computer, it will save to file each  time a request is made and you then have the ability to restore that file to overseerr.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by tobz** [comment]
@megasyntax Overseerr already stores all of its configuration and operational data, including requests, to a local SQLite database by default.

It sounds like you need to map the application directory in the container to a volume on disk so that the data can persist after you stop, delete, and recreate the container. The [Docker](https://docs.overseerr.dev/getting-started/installation#docker) installation steps show an example of this where `/app/config` is being mounted to a volume on the Docker host.

**Comment by danshilm** [comment]
Like tobz already mentioned, this is an issue with the configuration for Overseerr.
If you need more help, reach out on discord.
