### ISSUE TITLE
Add Telegram and Slack as a notification options

### ISSUE THREAD

**Issue by dpimente** [sct/overseerr#365]
**Is your feature request related to a problem? Please describe.**
I'd like to use telegram and Slack as a notification options as the majority of my users use it, currently this isn't supported

**Describe the solution you'd like**
Within 'settings' --> 'notification', Telegram and Slack would be added as an option beyond Discord and email

**Describe alternatives you've considered**
I've considered using email, but my users don't check that as much as a messaging app like telegram or Slack. Also thought about discord but nearly none of my users have it - so it would be a much bigger effort for adoption.

**Comment by Reddax** [comment]
This is a big one for me, slack especially

**Comment by ebartz** [comment]
Simple Webhooks would also be nice.

**Comment by ankarhem** [comment]
working on this

**Comment by sct** [comment]
While @ankarhem works on telegram I went and built out Slack. It will be in the next release!

**Comment by costaht** [comment]
@ankarhem just to let you know. Ombi only allows us to send notifications to a "group", which is not ideal.

So when Jakob requests a movie, **Jakob and I** will get the notification "Jakob requested movie X", then we both get the message "Costa approved your request", then "Your request for X is available".
All of that is sent not only to the Overseerr admin or to who requested the movie, but to everyone included in the group.

The ideal is that we could add the person's telegram username or their id to their Overseerr profile so they can get personal notifications, otherwise, people will just mute the group making it pointless

Thank you

**Comment by ankarhem** [comment]
@costaht 

 I think it's out of scope for now. The PR I did has the same functionality as ombi. It dumps everything into the chatid. This shouldn't need to be a group though? There are other things that can be improved upon as well, which can be done over time.

We can do a new issue with:
* Add telegram chatid to userprofiles.
* Send the notifications to the chatid on the user profile that the request originated from.

**Comment by costaht** [comment]
>   I think it's out of scope for now

Not a problem. Thank you.
 
> We can do a new issue with:
> 
> * Add telegram chatid to userprofiles.
> * Send the notifications to the chatid on the user profile (if it exists) that the request originated from.

Do you want me to open one ticket for each on only one for both? (considering that one depends on the other)

**Comment by ankarhem** [comment]
@costaht 
It's a single issue. I just did them as bullet points to try and split the idea into what parts would go into it.

**Comment by sct** [comment]
Both of these agents are merged into develop and will be in the next release.
