### ISSUE TITLE
Watchlist visible instantly but long wait time for the request

### ISSUE THREAD

**Issue by bertho-zero** [sct/overseerr#3754]
### Description

I activated the automatic request when adding a movie to the Plex watchlist, I see it arrive immediately on Overseerr app but the request takes between 14 and 24 minutes.

I activated the automatic request when adding a film to Plex, I see it arrive immediately on Overseerr but the request takes between 14 and 24 minutes.

### Desired Behavior

The ideal would be not to wait long before launching the request

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by stefangrosaru** [comment]
I'd like to know why the Job that does this is on a 20 minute non-negotiable timer.

I would've thought it's because some requests are made directly to Plex, but not sure if that is actually the case, since after adding something to my Plex watchlist it shows up within seconds in Overseer, but then to pass on the request to Radarr/Sonarr it takes a long time.

Why is that?

**Comment by utkarshsethi** [comment]
![image](https://github.com/sct/overseerr/assets/2989912/e602f221-a9f8-49ef-b1aa-3a79898c443e)


https://www.reddit.com/r/Overseerr/comments/173x8zn/comment/k46x0yv/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by ZDTaylor** [comment]
At least for Plex Pass holders,it should be possible to use the RSS feed for the watchlist, which should be lower-load and allow Overseerr to do watchlist imports way more frequently. Is that something that could be added?
Source: [Watchlistarr](https://github.com/nylonee/watchlistarr) does this to get near-immediate updates.
