### ISSUE TITLE
Some pages/elements aren't translateable

### ISSUE THREAD

**Issue by sebstrgg** [sct/overseerr#408]
**Describe the bug**
Some pages/text/elements aren't translatable

- Movie/Series Statuses should be translatable (e.q. Canceled, Released etc.)
- :christmas_tree:Happy Holidays!:christmas_tree:Category should be translatable
- Settings -> Logs page should be translatable
- Static elements of changelogs should be translatable

**Comment by sct** [comment]
> * Movie/Series Statuses should be translatable (e.q. Canceled, Released etc.)

As of right now these statuses come back directly from TMDB in this form. I could try to match the strings returned and replace them with translatable strings but it might be fragile.

> * 🎄Happy Holidays!🎄Category should be translatable

I left this untranslatable because it's very temporary. We were discussing some options on how to make interesting, dynamic blocks of titles on the DIscover page. If we come up with something more permanent, we can translate it.

> * Settings -> Logs page should be translatable

It's a temporary page and the full, real version of the logs page is being built. The real logs page will be localized.

> * Static elements of changelogs should be translatable

This data comes back straight from the GitHub releases API. We can't really translate this.
