### ISSUE TITLE
Idea: Advanced searching/filtering/sorting

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#459]
**Is your feature request related to a problem? Please describe.**
There a lot of good movies out there with high IMDb or Rotten tomatoes scores that doesn't make it to the the "mainstream" watchers. 
We have now some items on the page for popular or Popular Series. 
May i suggest to create a option for advanced searching/filtering by the end user? 
This will enable more suggestions to the end user that aren't mainstream and gives the end user more option to discover new good movies :)

**Describe the solution you'd like**
Button in the right corner of the search box with "advanced filtering".
If you click on it, a popup or dropdown will show with filtering options.

**Describe alternatives you've considered**
None

**Additional context**
See the discord talk in the feedback channel

**Comment by Magikarplvl4** [comment]
Don't close it please Stalebot :(

**Comment by kungfoome** [comment]
Yes please. Some ideas on filters:

- Show only TV Shows or Movies, probably make this a little bit more general to possibly support music and possibly books later on as well.
- Hide/Show available
- sort by tmdb/imdb/rottentomato ratings

Then eventually some more advanced stuff maybe. Like find by actor, director etc...

**Comment by SJPadbury** [comment]
Another idea on filters might be to have one to remove appearances as "self" to not have the results cluttered with every late night show in existence.
Also one to not show items already in the library in results would be good, as I find myself visually filtering out ones that are already there most of the time based on the icon for already being added/requested.

**Comment by kokozaurz** [comment]
Just to start would be amazing to toggle show available/unavailable. Otherwise hard to see through lists items that haven't been requested vs that have been or/and have been filled already.

**Comment by sct** [comment]
> Just to start would be amazing to toggle show available/unavailable. Otherwise hard to see through lists items that haven't been requested vs that have been or/and have been filled already.

You can already do this?

![image](https://user-images.githubusercontent.com/234213/119068828-e691cf00-ba1f-11eb-9e04-539c3067cfc0.png)

**Comment by kokozaurz** [comment]
> > Just to start would be amazing to toggle show available/unavailable. Otherwise hard to see through lists items that haven't been requested vs that have been or/and have been filled already.
> 
> You can already do this?
> 
> ![image](https://user-images.githubusercontent.com/234213/119068828-e691cf00-ba1f-11eb-9e04-539c3067cfc0.png)

ah - was looking around and couldn't find this feature just to realize it's under settings. this is great. I wish it also removed already requested items but this is already so much better. Thanks!

**Comment by Magikarplvl4** [comment]
Nooooh @sct help

**Comment by Nakda** [comment]
I was looking for something similar because"Upcoming Movies" is not sorting media chronologically. I'd love to tweak the underlying Tmdb API request according to my personal preferences.

Just to clarify this issue, is this a future implementation for end-users only, or could the admin tweak a section (eg Upcoming Movies) or add a new one with the custom request? I feel a permanent filtered view, or an admin-enforced setting would be fine, but having to re-apply my filters everytime would be painful.

If it can help, here's an example of the parameters I'd tweak:
- `primary_release_year` : to filter out old movies being re-released (4K, etc)
- `with_release_type`: I'm only interrested in digital releases (meaning they will probably be made available soon through Radarr, instead of Theater releases)
- `release_date.gte`: set to Today's date
- `sort_by`: set to `release_date.asc`

**Comment by g4m3r7ag** [comment]
Excluding Genres would be a good first step I think. I have the option enabled to not display items that are already available, and now instead of Popular shows listing a bunch of items I already have in my library, it just lists talk shows/soap operas/game shows.

**Comment by jeffery9876** [comment]
another useful filtering options are : 

   - region ( Japan, German )
   - language ( French, Spanish, Japanese, etc ), I don't want to change the language on my profile, but temporary searching for other languages 
   - release years
   - ratings

**Comment by cparello** [comment]
Sorting content when you click on a service like netflix or hbo max should show by release date descending. So much better if the new stuff is at the top of the list.

**Comment by Fedack** [comment]
Any updates on this? It's really weird it's lacking. It seems such a necessary feature.

**Comment by cparello** [comment]
@TheCatLady any chance we can ever get sorting? I can take alook if nobody is working on it

**Comment by sct** [comment]
> @TheCatLady any chance we can ever get sorting? I can take alook if nobody is working on it

As with any work we do on Overseerr, we are limited by our free time. It's still planned, and we have some ideas on how we want it implemented. If you are interested in contributing and think you could build the feature, that would be great! However, because there are already some thoughts about how we want this designed it needs to be done correctly.
