### ISSUE TITLE
Redesign requests management for mobile

### ISSUE THREAD

**Issue by ankarhem** [sct/overseerr#569]
This is mostly to start a discussion as I don't know if my suggestion is the best course of action.

**Is your feature request related to a problem? Please describe.**
The current design isn't very usable on mobile. This is what you see currently, and you need to scroll far to the right to see the additional information.
<img src="https://user-images.githubusercontent.com/14110063/103493205-2882f580-4e30-11eb-96f0-1aa4ca04b559.png" width="375px"/>

**Describe the solution you'd like**
One solution would be to implement a management similar to how mail are managed with actions via sliding.

<img src="https://media.discordapp.net/attachments/783137440809746485/795404335709945876/image1.png" width="375px" />

**Comment by sct** [comment]
Planning on reworking the current design for mobile. I am not sure how I feel about having any sliding action because mirroring native touch on the web is finicky at best.

My plan was just to have a different row render for mobile, that is designed to just show everything in more of a block format, than a long row.
