### ISSUE TITLE
Ability to decline request after approval

### ISSUE THREAD

**Issue by modem7** [sct/overseerr#572]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to decline request after approval. This would be useful when there aren't any sources, or all downloads fail. 

This would give the ability for users to receive a failed notification with a custom note that can be filled in by the admin such as "All sources failed, nothing available"

**Describe alternatives you've considered**
none

**Additional context**
N/A

**Comment by sct** [comment]
Do you not just leave your requests pending incase they eventually become available? By declining a users request, what should the user expect in this situation? To give up on ever having that content or to try again later?

**Comment by modem7** [comment]
In my particular case, yes.

A lot of this content are old things like 1950's movies and shows etc.
Things that just aren't popular or will never be uploaded rather than new
things that haven't hit indexers yet.

**Comment by modem7** [comment]
Bump to stop this going stale

**Comment by modem7** [comment]
Bump to stop this going stale

**Comment by srijan** [comment]
Bump. Can this be re-opened?

**Comment by kimfr** [comment]
I would also like this feature - as mentioned by others - my users sometimes requests old stuff which will never become available. From a "workflow" perspective, I approve and let the *arr's try their best - if that fails after sometime - I would like to inform the requester and cancel the request.

At the moment, the only option I know of is to delete the request in overseerr and manually remove from *arr - the problem is that the requester is NOT notified.
