### ISSUE TITLE
Bottom navigation for the mobile UI

### ISSUE THREAD

**Issue by ghost** [sct/overseerr#736]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Petio uses bottom navigation for their mobile UI and it just seems like the most logical and intuitive way to go about it. Practically every mobile app does it; requires less clicks and allows you to always have a full view of your current page.

![image](https://user-images.githubusercontent.com/56069014/105642907-d9f3d480-5e8c-11eb-9148-a3a1d11a973e.png)

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
There is no additional context.

**Comment by danshilm** [comment]
I don't think this will be possible because of the existing layout of Overseerr and how the space is occupied already.
This is a screenshot from a Galaxy S9 for example:

![S9 Example](https://cdn.discordapp.com/attachments/785475034725482498/796305100145819648/unknown.png)

Adding the bottom navigation row would result in so much of the page being covered up.

**Comment by sct** [comment]
Accomplishing this will mean rebuilding the entire layout for mobile. It's not out of the question, but it's going to be a while before we can even try to approach this.

**Comment by TheCatLady** [comment]
I'm possibly in the minority here, but I actually really like the way Overseerr looks on mobile.  I'm not really a fan of the bottom navigation.

**Comment by Wh1t3Rose** [comment]
@TheCatLady You are definitely in the minority, Bottom navigation is a must with today's large phones and makes one-hand operation not just better but actually viable,
