### ISSUE TITLE
Support for requesting TV show specials

### ISSUE THREAD

**Issue by Magikarplvl4** [sct/overseerr#779]
**Is your feature request related to a problem? Please describe.**
Currently, you can't request a special episode in Overseerr.
Is it possible to make an option available to request specials?

**Describe the solution you'd like**
Make it possible to the end-user to create an option to request specials.

**Describe alternatives you've considered**

**Additional context**

**Comment by danshilm** [comment]
Feature still wanted.

**Comment by brw** [comment]
It's been a while but I'd still like to see this. I often have people messaging me about specials, which are fairly common when it comes to anime.

**Comment by Magikarplvl4** [comment]
Can reopen this one? :(

**Comment by Aeramor** [comment]
This is what I was coming here to look for. 
Basically just needs to handle TV show movies as a dual lookup IMO. 
As an example: I have all the Futurama movies available on my plex but Overseerr shows them as not available because they are in Sonarr/Plex but not Radarr.
Sonarr/Radarr are incompatible for TV movies (radarr requires 1 movie per folder, Sonarr by default puts all specials in a single folder)
Even worse example: TV episodes that are labeled as movies. Like Stargate SG-1 True Science (first 3 eps of season 1)

I'll take a look at the code in a bit and see if I can either just do it or offer more helpful feedback.

**Comment by barrelltitor** [comment]
Would be great to see this added in, or at least a way to mark them as available so they won't be shown up in the discover section.

**Comment by SethGower** [comment]
@Aeramor 
> Like Stargate SG-1 True Science (first 3 eps of season 1)

This is exactly what caused me to go looking for a way to solve this issue. Have you found a way to get that outside of overseer?

**Comment by MrN0b0dy98** [comment]
Still interested!🙂

**Comment by bverkron** [comment]
Just [ran into this](https://github.com/sct/overseerr/discussions/3684). Surprised this isn't a feature already. Is it much different than just pulling regular seasons? The data seems to be there in tvDB.

**Comment by AhmedNSidd** [comment]
Just updating this issue to say that I'm looking into this...

**Comment by AhmedNSidd** [comment]
Huzzah! After ~3 years, we have a PR for this: https://github.com/sct/overseerr/pull/3724

Happy Holidays folks

**Comment by Pieter-BasDynatos** [comment]
> Huzzah! After ~3 years, we have a PR for this: #3724
> 
> Happy Holidays folks

<3
