### ISSUE TITLE
Add a new Notification Agent : Plex

### ISSUE THREAD

**Issue by WoisWoi** [sct/overseerr#876]
Hi :)

**Is your feature request related to a problem?**
No.
Right now, the available notification agents are : 

![image](https://user-images.githubusercontent.com/75491231/107161197-66c58480-699b-11eb-86c7-797a8f1affaf.png)

**Describe the solution you'd like**
It would be highly appreciable to have more of them, especially the plex app on mobile (iOS /Android) as Tautulli does : 

![image](https://user-images.githubusercontent.com/75491231/107161225-8e1c5180-699b-11eb-9cb1-12c51bc88446.png)

**Comment by sct** [comment]
What's the actual notification you expect here? I am not even sure how plex notifications work. I use plex's built in notifications when content is added to libraries. Is this different?

**Comment by WoisWoi** [comment]
> 
> 
> What's the actual notification you expect here? I am not even sure how plex notifications work. I use plex's built in notifications when content is added to libraries. Is this different?

I don't know either if it's possible, but tthe idea is : 
if enabled, users will receive the notification on/from Plex, that the content they requested on Overseerr is now available on Plex.

**Comment by costaht** [comment]
Plex has a feature on the mobile version that notifies users of new content added to the library.
 
**The issues are:**
- User need Plex app in their phone;
- By default these notifications are disabled;
- The notification goes to all users (don't know if you can pass any parameter).

**Comment by TheCatLady** [comment]
@costaht That's not really relevant to this feature request.  @WoisWoi is asking for Overseerr notifications via the Plex Android/iOS apps.  Apparently this is possible, since Tautulli has implemented it.

Also, just so you know -- the built-in Plex app notifications need to be enabled per device.  You are correct that they are disabled by default.

**Comment by samwiseg0** [comment]
This is possible but extremely limited. We were only able to use a few notifications. You also cannot modify most of the test as plex controls that on their side. The only notification that _could_ be useful is when media is available. 

These are the only 3 notifications Tautulli is utilizing. 
https://github.com/Tautulli/Tautulli/blob/master/plexpy/notifiers.py#L2404-L2408

**Comment by TheCatLady** [comment]
@samwiseg0 In that case, would Overseerr Plex notifications be useful at all?  Plex can natively send notifications when new media is added.

**Comment by WoisWoi** [comment]
> 
> 
> @samwiseg0 In that case, would Overseerr Plex notifications be useful at all? Plex can natively send notifications when new media is added.

It would be, if we can limit the notification to the requested media on Overseerr (from a specific user).

**Comment by TheCatLady** [comment]
> It would be, if we can limit the notification to the requested media on Overseerr and to the user that made the request.

Hm, I suppose.  Now, the issues I see are that:
1. Plex Pass is required for Plex Android/iOS notifications... do we have a way to check for that?  I don't think we do.
2. If a user has the built-in notifications already enabled within the Plex app, they will get duplicate notifications unless they disable those settings in the app.  We don't have a way to check for and handle this.  The [Tautulli documentation](https://github.com/Tautulli/Tautulli-Wiki/wiki/Notification-Agents-Guide#plexmobileapp) explains this, but do we expect every user to read a description about how to prevent this undesired behavior?  Our target users include both server admins _and_ end users, so we need to be more careful.

I think that if we want to add the Plex notification agent, it would require some warnings so that users do not complain about notifications (because they didn't disable the notification options within the Plex mobile app) or that they aren't receiving notifications (because they don't have Plex Pass).  Also, it would have to be dependent on user profiles being implemented, since we cannot just enable this globally for all users (because of the duplicate notification issue).

**Comment by sct** [comment]
I agree with @TheCatLady. The behavior here is confusing for the user. They would have to turn on notifications, which presents them with options of which notifications they want to receive. I imagine users turning on the "new content is added" option and getting notifications twice now because Overseerr sends it also. We would need documentation and a lot of hand-holding to explain how this works, and most end-users are not going to bother. If the end-user must visit any form of documentation to explain an option outside of the app, we are doing it wrong.
