### ISSUE TITLE
Overseerr availability misbehaving

### ISSUE THREAD

**Issue by WoisWoi** [sct/overseerr#990]
#### Description

Overseerr considers media (fully or partially) available to be also partially available in 4K.
I have only seen this problem with series (yet).

#### Version

develop-5acd91bc8e74eaacdf33dffa07dd10f1e53a9f8c

#### Steps to Reproduce

1. You need a media to be (fully or partially) available on your Plex library.
2. Run a full Sonarr scan + Plex scan
3. First, Overseerr correctly notes media availability via Sonarr, then adds this availability error with the Plex scan.

#### Expected Behavior

That the availability in 4K is not marked when it is simply not the case.

#### Screenshots

[Example of the problem](https://cdn.discordapp.com/attachments/789002037529804833/813189738625368136/unknown.png)
[Expected behavior](https://snipboard.io/6mcpqt.jpg)
Surprisingly, if the media had been requested and [I delete the request](https://cdn.discordapp.com/attachments/789002037529804833/813182135665688616/unknown.png), it [solves the problem](https://cdn.discordapp.com/attachments/789002037529804833/813182211167617034/unknown.png)

#### Device

- **Server on Linux Debian x64 AMD** 

#### Additional Context

The problem has been discussed on the Discord #support channel.
[Overseerr logs when I've reproduced the problem](https://gist.github.com/WoisWoi/8103ca2b2e2481d82e4bd9f8861e3e93)
[Plex XML file of one of the series concerned by the problem](https://gist.github.com/WoisWoi/fa5f1f3844ec63189d939c06bca37793)

**Comment by cpt-kuesel** [comment]
Hi, i am experiencing the same behavior.
Yesterday a user requested the show Black Sails and today I am importing 1080p Bluray episodes.
Overseerr now shows both Partially available as well as 4k Partially available, although request and episodes are only 1080p.
![black_sails_overseerr](https://user-images.githubusercontent.com/79487102/108985367-4252f300-7691-11eb-8b9a-33118e797c06.png)

Before the request was made i upgraded to the newest release 1.20.0.
My logs don't show anything special because they are only on info level unfortunately.
Here they are nevertheless: [Overserr Logs](https://gist.github.com/cpt-kuesel/46e2048214e51f37b8e3fc1bf9a8f40b)

Here are the Plex XML files of the show that are already imported: [Plex XMLs](https://gist.github.com/cpt-kuesel/3a61ebe169b1e78b116da42dec7b577b)

**Comment by sct** [comment]
Thanks for the detailed logs/xml @cpt-kuesel. I'm looking into it.

**Comment by sct** [comment]
This is fixed in `develop` now. The next sync should correctly update the status back to what it should be, but if it doesn't, you will need to reset the media data and sync again.

**Comment by cpt-kuesel** [comment]
Can confirm, after updating to 1.20.1 and another full library scan it shows the available status as it should!
