### ISSUE TITLE
Allow "open in *arr" to not specify the port in the URL

### ISSUE THREAD

**Issue by DanWillman** [sct/overseerr#996]
#### Description

Is your feature request related to a problem? **No**

I'm running my sonarr/radarr services, among other things, behind a reverse proxy like so: https://sonarr.mydomain.com, currently when using the "Open in Sonarr" link from a media entry Overseerr opens a new tab to https://sonarr.mydomain.com:8989

It may be worth noting, I currently am running overseerr on a different domain and docker instance. Ex: https://overseerr.anotherdomain.com

#### Desired Behavior

I would like an option, perhaps a toggle in the services settings page, that disables specifying the port in the URL when using "Open in *arr" from the media page.

**Comment by otravers** [comment]
I'm confused why this was refiled and closed as a support request. This is a request for new functionality, i.e. allow portless hostnames which is what those of us who use reverse proxies do, as described by the OP.

Port is currently a compulsory field, so not being able to input https://subdomain.domain.tld as a Sonarr server is currently working as intended, ergo this issue is not a bug report nor a support request but indeed a feature request. Please reconsider!

**Comment by DanWillman** [comment]
It did indeed end up being a support issue, it's already a feature that I missed. 

![image](https://user-images.githubusercontent.com/4489280/110003188-c46b9900-7cdb-11eb-833d-070a99dd68c1.png)

Appreciate the agreement though @otravers, glad to know I'm not the only one that missed it 😆
